/* @flow strict-local */
/* eslint-disable spellcheck/spell-checker */

/* This file was autogenerated by tools/generate-txn-import.js from
   static/translations/languages.yaml. Do not edit it directly. */

export type Language = {
  /** The locale, as named by react-intl. Not for display. */
  locale: string,
  /** The language's name in English. Transifex-translatable. */
  name: string,
  /** The language's name in the language itself. For raw display. */
  nativeName: string,
};

export const languageData: $ReadOnlyArray<Language> = [
  { locale: 'bg', name: 'Bulgarian', nativeName: 'Български' },
  { locale: 'ca', name: 'Catalan', nativeName: 'Català' },
  { locale: 'cs', name: 'Czech', nativeName: 'Čeština' },
  { locale: 'de', name: 'German', nativeName: 'Deutsch' },
  { locale: 'en', name: 'English', nativeName: 'English' },
  { locale: 'es', name: 'Spanish', nativeName: 'Español' },
  { locale: 'fa', name: 'Persian', nativeName: 'فارسی' },
  { locale: 'fi', name: 'Finnish', nativeName: 'Suomi' },
  { locale: 'fr', name: 'French', nativeName: 'Français' },
  { locale: 'gl', name: 'Galician', nativeName: 'Galego' },
  { locale: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { locale: 'hu', name: 'Hungarian', nativeName: 'Magyar' },
  { locale: 'id-ID', name: 'Indonesian', nativeName: 'Bahasa Indonesia' },
  { locale: 'it', name: 'Italian', nativeName: 'Italiano' },
  { locale: 'ja', name: 'Japanese', nativeName: '日本語' },
  { locale: 'ko', name: 'Korean', nativeName: '한국어' },
  { locale: 'lt', name: 'Lithuanian', nativeName: 'Lietuvių' },
  { locale: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { locale: 'nl', name: 'Dutch', nativeName: 'Nederlands' },
  { locale: 'pl', name: 'Polish', nativeName: 'Polski' },
  { locale: 'pt', name: 'Portuguese', nativeName: 'Português' },
  { locale: 'ro', name: 'Romanian', nativeName: 'Română' },
  { locale: 'ru', name: 'Russian', nativeName: 'Русский' },
  { locale: 'sr', name: 'Serbian', nativeName: 'Српски' },
  { locale: 'sv', name: 'Swedish', nativeName: 'Svenska' },
  { locale: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { locale: 'tr', name: 'Turkish', nativeName: 'Türkçe' },
  { locale: 'uk', name: 'Ukrainian', nativeName: 'Українська' },
  { locale: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt' },
  { locale: 'zh-Hans', name: 'Chinese (Simplified)', nativeName: '中文 (简体)' },
  { locale: 'zh-Hant', name: 'Chinese (Traditional)', nativeName: '中文 (繁体)' },
];
