// flow-typed signature: bc0e7d59fd3f1896dddd741104e22cd8
// flow-typed version: <<STUB>>/@sentry/react-native_v^1.0.9/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@sentry/react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@sentry/react-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@sentry/react-native/dist/js/backend' {
  declare module.exports: any;
}

declare module '@sentry/react-native/dist/js/client' {
  declare module.exports: any;
}

declare module '@sentry/react-native/dist/js' {
  declare module.exports: any;
}

declare module '@sentry/react-native/dist/js/integrations/debugsymbolicator' {
  declare module.exports: any;
}

declare module '@sentry/react-native/dist/js/integrations/devicecontext' {
  declare module.exports: any;
}

declare module '@sentry/react-native/dist/js/integrations' {
  declare module.exports: any;
}

declare module '@sentry/react-native/dist/js/integrations/reactnativeerrorhandlers' {
  declare module.exports: any;
}

declare module '@sentry/react-native/dist/js/integrations/release' {
  declare module.exports: any;
}

declare module '@sentry/react-native/dist/js/sdk' {
  declare module.exports: any;
}

declare module '@sentry/react-native/dist/js/transports/native' {
  declare module.exports: any;
}

declare module '@sentry/react-native/dist/js/version' {
  declare module.exports: any;
}

declare module '@sentry/react-native/react-native.config' {
  declare module.exports: any;
}

declare module '@sentry/react-native/scripts/version-bump' {
  declare module.exports: any;
}

// Filename aliases
declare module '@sentry/react-native/dist/js/backend.js' {
  declare module.exports: $Exports<'@sentry/react-native/dist/js/backend'>;
}
declare module '@sentry/react-native/dist/js/client.js' {
  declare module.exports: $Exports<'@sentry/react-native/dist/js/client'>;
}
declare module '@sentry/react-native/dist/js/index' {
  declare module.exports: $Exports<'@sentry/react-native/dist/js'>;
}
declare module '@sentry/react-native/dist/js/index.js' {
  declare module.exports: $Exports<'@sentry/react-native/dist/js'>;
}
declare module '@sentry/react-native/dist/js/integrations/debugsymbolicator.js' {
  declare module.exports: $Exports<'@sentry/react-native/dist/js/integrations/debugsymbolicator'>;
}
declare module '@sentry/react-native/dist/js/integrations/devicecontext.js' {
  declare module.exports: $Exports<'@sentry/react-native/dist/js/integrations/devicecontext'>;
}
declare module '@sentry/react-native/dist/js/integrations/index' {
  declare module.exports: $Exports<'@sentry/react-native/dist/js/integrations'>;
}
declare module '@sentry/react-native/dist/js/integrations/index.js' {
  declare module.exports: $Exports<'@sentry/react-native/dist/js/integrations'>;
}
declare module '@sentry/react-native/dist/js/integrations/reactnativeerrorhandlers.js' {
  declare module.exports: $Exports<'@sentry/react-native/dist/js/integrations/reactnativeerrorhandlers'>;
}
declare module '@sentry/react-native/dist/js/integrations/release.js' {
  declare module.exports: $Exports<'@sentry/react-native/dist/js/integrations/release'>;
}
declare module '@sentry/react-native/dist/js/sdk.js' {
  declare module.exports: $Exports<'@sentry/react-native/dist/js/sdk'>;
}
declare module '@sentry/react-native/dist/js/transports/native.js' {
  declare module.exports: $Exports<'@sentry/react-native/dist/js/transports/native'>;
}
declare module '@sentry/react-native/dist/js/version.js' {
  declare module.exports: $Exports<'@sentry/react-native/dist/js/version'>;
}
declare module '@sentry/react-native/react-native.config.js' {
  declare module.exports: $Exports<'@sentry/react-native/react-native.config'>;
}
declare module '@sentry/react-native/scripts/version-bump.js' {
  declare module.exports: $Exports<'@sentry/react-native/scripts/version-bump'>;
}
