// flow-typed signature: 0ee03e6e651726bc68f78bcb290cbb39
// flow-typed version: <<STUB>>/detox_v^5.8.1/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'detox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'detox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'detox/lib/android/expect' {
  declare module.exports: any;
}

declare module 'detox/lib/android/expect.test' {
  declare module.exports: any;
}

declare module 'detox/lib/android/matcher' {
  declare module.exports: any;
}

declare module 'detox/lib/artifacts/ArtifactsCopier' {
  declare module.exports: any;
}

declare module 'detox/lib/artifacts/ArtifactsPathsProvider' {
  declare module.exports: any;
}

declare module 'detox/lib/artifacts/ArtifactsPathsProvider.test' {
  declare module.exports: any;
}

declare module 'detox/lib/client/actions/actions' {
  declare module.exports: any;
}

declare module 'detox/lib/client/AsyncWebSocket' {
  declare module.exports: any;
}

declare module 'detox/lib/client/AsyncWebSocket.test' {
  declare module.exports: any;
}

declare module 'detox/lib/client/Client' {
  declare module.exports: any;
}

declare module 'detox/lib/client/Client.test' {
  declare module.exports: any;
}

declare module 'detox/lib/configuration' {
  declare module.exports: any;
}

declare module 'detox/lib/configuration.test' {
  declare module.exports: any;
}

declare module 'detox/lib/configurations.mock' {
  declare module.exports: any;
}

declare module 'detox/lib/Detox' {
  declare module.exports: any;
}

declare module 'detox/lib/Detox.test' {
  declare module.exports: any;
}

declare module 'detox/lib/devices/android/AAPT' {
  declare module.exports: any;
}

declare module 'detox/lib/devices/android/AAPT.test' {
  declare module.exports: any;
}

declare module 'detox/lib/devices/android/ADB' {
  declare module.exports: any;
}

declare module 'detox/lib/devices/android/ADB.test' {
  declare module.exports: any;
}

declare module 'detox/lib/devices/android/Emulator' {
  declare module.exports: any;
}

declare module 'detox/lib/devices/android/EmulatorTelnet' {
  declare module.exports: any;
}

declare module 'detox/lib/devices/AndroidDriver' {
  declare module.exports: any;
}

declare module 'detox/lib/devices/AppleSimUtils' {
  declare module.exports: any;
}

declare module 'detox/lib/devices/AppleSimUtils.test' {
  declare module.exports: any;
}

declare module 'detox/lib/devices/Device' {
  declare module.exports: any;
}

declare module 'detox/lib/devices/Device.test' {
  declare module.exports: any;
}

declare module 'detox/lib/devices/DeviceDriverBase' {
  declare module.exports: any;
}

declare module 'detox/lib/devices/EmulatorDriver' {
  declare module.exports: any;
}

declare module 'detox/lib/devices/IosDriver' {
  declare module.exports: any;
}

declare module 'detox/lib/devices/SimulatorDriver' {
  declare module.exports: any;
}

declare module 'detox/lib/errors/CustomError' {
  declare module.exports: any;
}

declare module 'detox/lib/errors/CustomError.test' {
  declare module.exports: any;
}

declare module 'detox/lib/index' {
  declare module.exports: any;
}

declare module 'detox/lib/index.test' {
  declare module.exports: any;
}

declare module 'detox/lib/invoke' {
  declare module.exports: any;
}

declare module 'detox/lib/invoke.test' {
  declare module.exports: any;
}

declare module 'detox/lib/invoke/EarlGrey' {
  declare module.exports: any;
}

declare module 'detox/lib/invoke/Espresso' {
  declare module.exports: any;
}

declare module 'detox/lib/invoke/Invoke' {
  declare module.exports: any;
}

declare module 'detox/lib/ios/earlgreyapi/GREYActions' {
  declare module.exports: any;
}

declare module 'detox/lib/ios/earlgreyapi/GREYConfiguration' {
  declare module.exports: any;
}

declare module 'detox/lib/ios/expect' {
  declare module.exports: any;
}

declare module 'detox/lib/ios/expect.test' {
  declare module.exports: any;
}

declare module 'detox/lib/ios/matchers' {
  declare module.exports: any;
}

declare module 'detox/lib/utils/argparse' {
  declare module.exports: any;
}

declare module 'detox/lib/utils/argparse.test' {
  declare module.exports: any;
}

declare module 'detox/lib/utils/environment' {
  declare module.exports: any;
}

declare module 'detox/lib/utils/environment.test' {
  declare module.exports: any;
}

declare module 'detox/lib/utils/exec' {
  declare module.exports: any;
}

declare module 'detox/lib/utils/exec.test' {
  declare module.exports: any;
}

declare module 'detox/lib/utils/fsext' {
  declare module.exports: any;
}

declare module 'detox/lib/utils/retry' {
  declare module.exports: any;
}

declare module 'detox/lib/utils/retry.test' {
  declare module.exports: any;
}

declare module 'detox/lib/utils/sh' {
  declare module.exports: any;
}

declare module 'detox/lib/utils/sh.test' {
  declare module.exports: any;
}

declare module 'detox/lib/utils/uuid' {
  declare module.exports: any;
}

declare module 'detox/local-cli/detox-build' {
  declare module.exports: any;
}

declare module 'detox/local-cli/detox-clean-framework-cache' {
  declare module.exports: any;
}

declare module 'detox/local-cli/detox-init' {
  declare module.exports: any;
}

declare module 'detox/local-cli/detox-run-server' {
  declare module.exports: any;
}

declare module 'detox/local-cli/detox-test' {
  declare module.exports: any;
}

declare module 'detox/local-cli/detox' {
  declare module.exports: any;
}

declare module 'detox/local-cli/templates/mocha' {
  declare module.exports: any;
}

declare module 'detox/src/android/expect' {
  declare module.exports: any;
}

declare module 'detox/src/android/matcher' {
  declare module.exports: any;
}

declare module 'detox/src/artifacts/ArtifactsCopier' {
  declare module.exports: any;
}

declare module 'detox/src/artifacts/ArtifactsPathsProvider' {
  declare module.exports: any;
}

declare module 'detox/src/client/actions/actions' {
  declare module.exports: any;
}

declare module 'detox/src/client/AsyncWebSocket' {
  declare module.exports: any;
}

declare module 'detox/src/client/Client' {
  declare module.exports: any;
}

declare module 'detox/src/configuration' {
  declare module.exports: any;
}

declare module 'detox/src/configurations.mock' {
  declare module.exports: any;
}

declare module 'detox/src/Detox' {
  declare module.exports: any;
}

declare module 'detox/src/devices/android/AAPT' {
  declare module.exports: any;
}

declare module 'detox/src/devices/android/ADB' {
  declare module.exports: any;
}

declare module 'detox/src/devices/android/Emulator' {
  declare module.exports: any;
}

declare module 'detox/src/devices/android/EmulatorTelnet' {
  declare module.exports: any;
}

declare module 'detox/src/devices/AndroidDriver' {
  declare module.exports: any;
}

declare module 'detox/src/devices/AppleSimUtils' {
  declare module.exports: any;
}

declare module 'detox/src/devices/Device' {
  declare module.exports: any;
}

declare module 'detox/src/devices/DeviceDriverBase' {
  declare module.exports: any;
}

declare module 'detox/src/devices/EmulatorDriver' {
  declare module.exports: any;
}

declare module 'detox/src/devices/IosDriver' {
  declare module.exports: any;
}

declare module 'detox/src/devices/SimulatorDriver' {
  declare module.exports: any;
}

declare module 'detox/src/errors/CustomError' {
  declare module.exports: any;
}

declare module 'detox/src/index' {
  declare module.exports: any;
}

declare module 'detox/src/invoke' {
  declare module.exports: any;
}

declare module 'detox/src/invoke/EarlGrey' {
  declare module.exports: any;
}

declare module 'detox/src/invoke/Espresso' {
  declare module.exports: any;
}

declare module 'detox/src/invoke/Invoke' {
  declare module.exports: any;
}

declare module 'detox/src/ios/earlgreyapi/GREYActions' {
  declare module.exports: any;
}

declare module 'detox/src/ios/earlgreyapi/GREYConfiguration' {
  declare module.exports: any;
}

declare module 'detox/src/ios/expect' {
  declare module.exports: any;
}

declare module 'detox/src/ios/matchers' {
  declare module.exports: any;
}

declare module 'detox/src/utils/argparse' {
  declare module.exports: any;
}

declare module 'detox/src/utils/environment' {
  declare module.exports: any;
}

declare module 'detox/src/utils/exec' {
  declare module.exports: any;
}

declare module 'detox/src/utils/fsext' {
  declare module.exports: any;
}

declare module 'detox/src/utils/retry' {
  declare module.exports: any;
}

declare module 'detox/src/utils/sh' {
  declare module.exports: any;
}

declare module 'detox/src/utils/uuid' {
  declare module.exports: any;
}

declare module 'detox/wallaby' {
  declare module.exports: any;
}

// Filename aliases
declare module 'detox/lib/android/expect.js' {
  declare module.exports: $Exports<'detox/lib/android/expect'>;
}
declare module 'detox/lib/android/expect.test.js' {
  declare module.exports: $Exports<'detox/lib/android/expect.test'>;
}
declare module 'detox/lib/android/matcher.js' {
  declare module.exports: $Exports<'detox/lib/android/matcher'>;
}
declare module 'detox/lib/artifacts/ArtifactsCopier.js' {
  declare module.exports: $Exports<'detox/lib/artifacts/ArtifactsCopier'>;
}
declare module 'detox/lib/artifacts/ArtifactsPathsProvider.js' {
  declare module.exports: $Exports<'detox/lib/artifacts/ArtifactsPathsProvider'>;
}
declare module 'detox/lib/artifacts/ArtifactsPathsProvider.test.js' {
  declare module.exports: $Exports<'detox/lib/artifacts/ArtifactsPathsProvider.test'>;
}
declare module 'detox/lib/client/actions/actions.js' {
  declare module.exports: $Exports<'detox/lib/client/actions/actions'>;
}
declare module 'detox/lib/client/AsyncWebSocket.js' {
  declare module.exports: $Exports<'detox/lib/client/AsyncWebSocket'>;
}
declare module 'detox/lib/client/AsyncWebSocket.test.js' {
  declare module.exports: $Exports<'detox/lib/client/AsyncWebSocket.test'>;
}
declare module 'detox/lib/client/Client.js' {
  declare module.exports: $Exports<'detox/lib/client/Client'>;
}
declare module 'detox/lib/client/Client.test.js' {
  declare module.exports: $Exports<'detox/lib/client/Client.test'>;
}
declare module 'detox/lib/configuration.js' {
  declare module.exports: $Exports<'detox/lib/configuration'>;
}
declare module 'detox/lib/configuration.test.js' {
  declare module.exports: $Exports<'detox/lib/configuration.test'>;
}
declare module 'detox/lib/configurations.mock.js' {
  declare module.exports: $Exports<'detox/lib/configurations.mock'>;
}
declare module 'detox/lib/Detox.js' {
  declare module.exports: $Exports<'detox/lib/Detox'>;
}
declare module 'detox/lib/Detox.test.js' {
  declare module.exports: $Exports<'detox/lib/Detox.test'>;
}
declare module 'detox/lib/devices/android/AAPT.js' {
  declare module.exports: $Exports<'detox/lib/devices/android/AAPT'>;
}
declare module 'detox/lib/devices/android/AAPT.test.js' {
  declare module.exports: $Exports<'detox/lib/devices/android/AAPT.test'>;
}
declare module 'detox/lib/devices/android/ADB.js' {
  declare module.exports: $Exports<'detox/lib/devices/android/ADB'>;
}
declare module 'detox/lib/devices/android/ADB.test.js' {
  declare module.exports: $Exports<'detox/lib/devices/android/ADB.test'>;
}
declare module 'detox/lib/devices/android/Emulator.js' {
  declare module.exports: $Exports<'detox/lib/devices/android/Emulator'>;
}
declare module 'detox/lib/devices/android/EmulatorTelnet.js' {
  declare module.exports: $Exports<'detox/lib/devices/android/EmulatorTelnet'>;
}
declare module 'detox/lib/devices/AndroidDriver.js' {
  declare module.exports: $Exports<'detox/lib/devices/AndroidDriver'>;
}
declare module 'detox/lib/devices/AppleSimUtils.js' {
  declare module.exports: $Exports<'detox/lib/devices/AppleSimUtils'>;
}
declare module 'detox/lib/devices/AppleSimUtils.test.js' {
  declare module.exports: $Exports<'detox/lib/devices/AppleSimUtils.test'>;
}
declare module 'detox/lib/devices/Device.js' {
  declare module.exports: $Exports<'detox/lib/devices/Device'>;
}
declare module 'detox/lib/devices/Device.test.js' {
  declare module.exports: $Exports<'detox/lib/devices/Device.test'>;
}
declare module 'detox/lib/devices/DeviceDriverBase.js' {
  declare module.exports: $Exports<'detox/lib/devices/DeviceDriverBase'>;
}
declare module 'detox/lib/devices/EmulatorDriver.js' {
  declare module.exports: $Exports<'detox/lib/devices/EmulatorDriver'>;
}
declare module 'detox/lib/devices/IosDriver.js' {
  declare module.exports: $Exports<'detox/lib/devices/IosDriver'>;
}
declare module 'detox/lib/devices/SimulatorDriver.js' {
  declare module.exports: $Exports<'detox/lib/devices/SimulatorDriver'>;
}
declare module 'detox/lib/errors/CustomError.js' {
  declare module.exports: $Exports<'detox/lib/errors/CustomError'>;
}
declare module 'detox/lib/errors/CustomError.test.js' {
  declare module.exports: $Exports<'detox/lib/errors/CustomError.test'>;
}
declare module 'detox/lib/index.js' {
  declare module.exports: $Exports<'detox/lib/index'>;
}
declare module 'detox/lib/index.test.js' {
  declare module.exports: $Exports<'detox/lib/index.test'>;
}
declare module 'detox/lib/invoke.js' {
  declare module.exports: $Exports<'detox/lib/invoke'>;
}
declare module 'detox/lib/invoke.test.js' {
  declare module.exports: $Exports<'detox/lib/invoke.test'>;
}
declare module 'detox/lib/invoke/EarlGrey.js' {
  declare module.exports: $Exports<'detox/lib/invoke/EarlGrey'>;
}
declare module 'detox/lib/invoke/Espresso.js' {
  declare module.exports: $Exports<'detox/lib/invoke/Espresso'>;
}
declare module 'detox/lib/invoke/Invoke.js' {
  declare module.exports: $Exports<'detox/lib/invoke/Invoke'>;
}
declare module 'detox/lib/ios/earlgreyapi/GREYActions.js' {
  declare module.exports: $Exports<'detox/lib/ios/earlgreyapi/GREYActions'>;
}
declare module 'detox/lib/ios/earlgreyapi/GREYConfiguration.js' {
  declare module.exports: $Exports<'detox/lib/ios/earlgreyapi/GREYConfiguration'>;
}
declare module 'detox/lib/ios/expect.js' {
  declare module.exports: $Exports<'detox/lib/ios/expect'>;
}
declare module 'detox/lib/ios/expect.test.js' {
  declare module.exports: $Exports<'detox/lib/ios/expect.test'>;
}
declare module 'detox/lib/ios/matchers.js' {
  declare module.exports: $Exports<'detox/lib/ios/matchers'>;
}
declare module 'detox/lib/utils/argparse.js' {
  declare module.exports: $Exports<'detox/lib/utils/argparse'>;
}
declare module 'detox/lib/utils/argparse.test.js' {
  declare module.exports: $Exports<'detox/lib/utils/argparse.test'>;
}
declare module 'detox/lib/utils/environment.js' {
  declare module.exports: $Exports<'detox/lib/utils/environment'>;
}
declare module 'detox/lib/utils/environment.test.js' {
  declare module.exports: $Exports<'detox/lib/utils/environment.test'>;
}
declare module 'detox/lib/utils/exec.js' {
  declare module.exports: $Exports<'detox/lib/utils/exec'>;
}
declare module 'detox/lib/utils/exec.test.js' {
  declare module.exports: $Exports<'detox/lib/utils/exec.test'>;
}
declare module 'detox/lib/utils/fsext.js' {
  declare module.exports: $Exports<'detox/lib/utils/fsext'>;
}
declare module 'detox/lib/utils/retry.js' {
  declare module.exports: $Exports<'detox/lib/utils/retry'>;
}
declare module 'detox/lib/utils/retry.test.js' {
  declare module.exports: $Exports<'detox/lib/utils/retry.test'>;
}
declare module 'detox/lib/utils/sh.js' {
  declare module.exports: $Exports<'detox/lib/utils/sh'>;
}
declare module 'detox/lib/utils/sh.test.js' {
  declare module.exports: $Exports<'detox/lib/utils/sh.test'>;
}
declare module 'detox/lib/utils/uuid.js' {
  declare module.exports: $Exports<'detox/lib/utils/uuid'>;
}
declare module 'detox/local-cli/detox-build.js' {
  declare module.exports: $Exports<'detox/local-cli/detox-build'>;
}
declare module 'detox/local-cli/detox-clean-framework-cache.js' {
  declare module.exports: $Exports<'detox/local-cli/detox-clean-framework-cache'>;
}
declare module 'detox/local-cli/detox-init.js' {
  declare module.exports: $Exports<'detox/local-cli/detox-init'>;
}
declare module 'detox/local-cli/detox-run-server.js' {
  declare module.exports: $Exports<'detox/local-cli/detox-run-server'>;
}
declare module 'detox/local-cli/detox-test.js' {
  declare module.exports: $Exports<'detox/local-cli/detox-test'>;
}
declare module 'detox/local-cli/detox.js' {
  declare module.exports: $Exports<'detox/local-cli/detox'>;
}
declare module 'detox/local-cli/templates/mocha.js' {
  declare module.exports: $Exports<'detox/local-cli/templates/mocha'>;
}
declare module 'detox/src/android/expect.js' {
  declare module.exports: $Exports<'detox/src/android/expect'>;
}
declare module 'detox/src/android/matcher.js' {
  declare module.exports: $Exports<'detox/src/android/matcher'>;
}
declare module 'detox/src/artifacts/ArtifactsCopier.js' {
  declare module.exports: $Exports<'detox/src/artifacts/ArtifactsCopier'>;
}
declare module 'detox/src/artifacts/ArtifactsPathsProvider.js' {
  declare module.exports: $Exports<'detox/src/artifacts/ArtifactsPathsProvider'>;
}
declare module 'detox/src/client/actions/actions.js' {
  declare module.exports: $Exports<'detox/src/client/actions/actions'>;
}
declare module 'detox/src/client/AsyncWebSocket.js' {
  declare module.exports: $Exports<'detox/src/client/AsyncWebSocket'>;
}
declare module 'detox/src/client/Client.js' {
  declare module.exports: $Exports<'detox/src/client/Client'>;
}
declare module 'detox/src/configuration.js' {
  declare module.exports: $Exports<'detox/src/configuration'>;
}
declare module 'detox/src/configurations.mock.js' {
  declare module.exports: $Exports<'detox/src/configurations.mock'>;
}
declare module 'detox/src/Detox.js' {
  declare module.exports: $Exports<'detox/src/Detox'>;
}
declare module 'detox/src/devices/android/AAPT.js' {
  declare module.exports: $Exports<'detox/src/devices/android/AAPT'>;
}
declare module 'detox/src/devices/android/ADB.js' {
  declare module.exports: $Exports<'detox/src/devices/android/ADB'>;
}
declare module 'detox/src/devices/android/Emulator.js' {
  declare module.exports: $Exports<'detox/src/devices/android/Emulator'>;
}
declare module 'detox/src/devices/android/EmulatorTelnet.js' {
  declare module.exports: $Exports<'detox/src/devices/android/EmulatorTelnet'>;
}
declare module 'detox/src/devices/AndroidDriver.js' {
  declare module.exports: $Exports<'detox/src/devices/AndroidDriver'>;
}
declare module 'detox/src/devices/AppleSimUtils.js' {
  declare module.exports: $Exports<'detox/src/devices/AppleSimUtils'>;
}
declare module 'detox/src/devices/Device.js' {
  declare module.exports: $Exports<'detox/src/devices/Device'>;
}
declare module 'detox/src/devices/DeviceDriverBase.js' {
  declare module.exports: $Exports<'detox/src/devices/DeviceDriverBase'>;
}
declare module 'detox/src/devices/EmulatorDriver.js' {
  declare module.exports: $Exports<'detox/src/devices/EmulatorDriver'>;
}
declare module 'detox/src/devices/IosDriver.js' {
  declare module.exports: $Exports<'detox/src/devices/IosDriver'>;
}
declare module 'detox/src/devices/SimulatorDriver.js' {
  declare module.exports: $Exports<'detox/src/devices/SimulatorDriver'>;
}
declare module 'detox/src/errors/CustomError.js' {
  declare module.exports: $Exports<'detox/src/errors/CustomError'>;
}
declare module 'detox/src/index.js' {
  declare module.exports: $Exports<'detox/src/index'>;
}
declare module 'detox/src/invoke.js' {
  declare module.exports: $Exports<'detox/src/invoke'>;
}
declare module 'detox/src/invoke/EarlGrey.js' {
  declare module.exports: $Exports<'detox/src/invoke/EarlGrey'>;
}
declare module 'detox/src/invoke/Espresso.js' {
  declare module.exports: $Exports<'detox/src/invoke/Espresso'>;
}
declare module 'detox/src/invoke/Invoke.js' {
  declare module.exports: $Exports<'detox/src/invoke/Invoke'>;
}
declare module 'detox/src/ios/earlgreyapi/GREYActions.js' {
  declare module.exports: $Exports<'detox/src/ios/earlgreyapi/GREYActions'>;
}
declare module 'detox/src/ios/earlgreyapi/GREYConfiguration.js' {
  declare module.exports: $Exports<'detox/src/ios/earlgreyapi/GREYConfiguration'>;
}
declare module 'detox/src/ios/expect.js' {
  declare module.exports: $Exports<'detox/src/ios/expect'>;
}
declare module 'detox/src/ios/matchers.js' {
  declare module.exports: $Exports<'detox/src/ios/matchers'>;
}
declare module 'detox/src/utils/argparse.js' {
  declare module.exports: $Exports<'detox/src/utils/argparse'>;
}
declare module 'detox/src/utils/environment.js' {
  declare module.exports: $Exports<'detox/src/utils/environment'>;
}
declare module 'detox/src/utils/exec.js' {
  declare module.exports: $Exports<'detox/src/utils/exec'>;
}
declare module 'detox/src/utils/fsext.js' {
  declare module.exports: $Exports<'detox/src/utils/fsext'>;
}
declare module 'detox/src/utils/retry.js' {
  declare module.exports: $Exports<'detox/src/utils/retry'>;
}
declare module 'detox/src/utils/sh.js' {
  declare module.exports: $Exports<'detox/src/utils/sh'>;
}
declare module 'detox/src/utils/uuid.js' {
  declare module.exports: $Exports<'detox/src/utils/uuid'>;
}
declare module 'detox/wallaby.js' {
  declare module.exports: $Exports<'detox/wallaby'>;
}
