// flow-typed signature: 6491c627cf6ecb58ee3c3ba5549ffc2e
// flow-typed version: <<STUB>>/detox_v^7.0.1/flow_v0.63.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'detox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'detox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'detox/local-cli/detox-build-framework-cache' {
  declare module.exports: any;
}

declare module 'detox/local-cli/detox-build' {
  declare module.exports: any;
}

declare module 'detox/local-cli/detox-clean-framework-cache' {
  declare module.exports: any;
}

declare module 'detox/local-cli/detox-init' {
  declare module.exports: any;
}

declare module 'detox/local-cli/detox-run-server' {
  declare module.exports: any;
}

declare module 'detox/local-cli/detox-test' {
  declare module.exports: any;
}

declare module 'detox/local-cli/detox' {
  declare module.exports: any;
}

declare module 'detox/local-cli/templates/mocha' {
  declare module.exports: any;
}

declare module 'detox/src/android/espressoapi/DetoxAction' {
  declare module.exports: any;
}

declare module 'detox/src/android/espressoapi/DetoxMatcher' {
  declare module.exports: any;
}

declare module 'detox/src/android/espressoapi/ViewActions' {
  declare module.exports: any;
}

declare module 'detox/src/android/expect' {
  declare module.exports: any;
}

declare module 'detox/src/android/matcher' {
  declare module.exports: any;
}

declare module 'detox/src/artifacts/ArtifactsCopier' {
  declare module.exports: any;
}

declare module 'detox/src/artifacts/ArtifactsPathsProvider' {
  declare module.exports: any;
}

declare module 'detox/src/client/actions/actions' {
  declare module.exports: any;
}

declare module 'detox/src/client/AsyncWebSocket' {
  declare module.exports: any;
}

declare module 'detox/src/client/Client' {
  declare module.exports: any;
}

declare module 'detox/src/configuration' {
  declare module.exports: any;
}

declare module 'detox/src/configurations.mock' {
  declare module.exports: any;
}

declare module 'detox/src/Detox' {
  declare module.exports: any;
}

declare module 'detox/src/devices/android/AAPT' {
  declare module.exports: any;
}

declare module 'detox/src/devices/android/ADB' {
  declare module.exports: any;
}

declare module 'detox/src/devices/android/APKPath' {
  declare module.exports: any;
}

declare module 'detox/src/devices/android/Emulator' {
  declare module.exports: any;
}

declare module 'detox/src/devices/android/EmulatorTelnet' {
  declare module.exports: any;
}

declare module 'detox/src/devices/AndroidDriver' {
  declare module.exports: any;
}

declare module 'detox/src/devices/AppleSimUtils' {
  declare module.exports: any;
}

declare module 'detox/src/devices/AttachedAndroidDriver' {
  declare module.exports: any;
}

declare module 'detox/src/devices/Device' {
  declare module.exports: any;
}

declare module 'detox/src/devices/DeviceDriverBase' {
  declare module.exports: any;
}

declare module 'detox/src/devices/EmulatorDriver' {
  declare module.exports: any;
}

declare module 'detox/src/devices/IosDriver' {
  declare module.exports: any;
}

declare module 'detox/src/devices/SimulatorDriver' {
  declare module.exports: any;
}

declare module 'detox/src/errors/CustomError' {
  declare module.exports: any;
}

declare module 'detox/src/exportWrapper' {
  declare module.exports: any;
}

declare module 'detox/src/index' {
  declare module.exports: any;
}

declare module 'detox/src/invoke' {
  declare module.exports: any;
}

declare module 'detox/src/invoke/EarlGrey' {
  declare module.exports: any;
}

declare module 'detox/src/invoke/Espresso' {
  declare module.exports: any;
}

declare module 'detox/src/invoke/Invoke' {
  declare module.exports: any;
}

declare module 'detox/src/ios/earlgreyapi/GREYActions' {
  declare module.exports: any;
}

declare module 'detox/src/ios/earlgreyapi/GREYConfiguration' {
  declare module.exports: any;
}

declare module 'detox/src/ios/earlgreyapi/GREYMatchers' {
  declare module.exports: any;
}

declare module 'detox/src/ios/earlgreyapi/GREYMatchers+Detox' {
  declare module.exports: any;
}

declare module 'detox/src/ios/expect' {
  declare module.exports: any;
}

declare module 'detox/src/ios/matchers' {
  declare module.exports: any;
}

declare module 'detox/src/platform' {
  declare module.exports: any;
}

declare module 'detox/src/utils/argparse' {
  declare module.exports: any;
}

declare module 'detox/src/utils/environment' {
  declare module.exports: any;
}

declare module 'detox/src/utils/exec' {
  declare module.exports: any;
}

declare module 'detox/src/utils/fsext' {
  declare module.exports: any;
}

declare module 'detox/src/utils/retry' {
  declare module.exports: any;
}

declare module 'detox/src/utils/sh' {
  declare module.exports: any;
}

declare module 'detox/src/utils/uuid' {
  declare module.exports: any;
}

declare module 'detox/wallaby' {
  declare module.exports: any;
}

// Filename aliases
declare module 'detox/local-cli/detox-build-framework-cache.js' {
  declare module.exports: $Exports<'detox/local-cli/detox-build-framework-cache'>;
}
declare module 'detox/local-cli/detox-build.js' {
  declare module.exports: $Exports<'detox/local-cli/detox-build'>;
}
declare module 'detox/local-cli/detox-clean-framework-cache.js' {
  declare module.exports: $Exports<'detox/local-cli/detox-clean-framework-cache'>;
}
declare module 'detox/local-cli/detox-init.js' {
  declare module.exports: $Exports<'detox/local-cli/detox-init'>;
}
declare module 'detox/local-cli/detox-run-server.js' {
  declare module.exports: $Exports<'detox/local-cli/detox-run-server'>;
}
declare module 'detox/local-cli/detox-test.js' {
  declare module.exports: $Exports<'detox/local-cli/detox-test'>;
}
declare module 'detox/local-cli/detox.js' {
  declare module.exports: $Exports<'detox/local-cli/detox'>;
}
declare module 'detox/local-cli/templates/mocha.js' {
  declare module.exports: $Exports<'detox/local-cli/templates/mocha'>;
}
declare module 'detox/src/android/espressoapi/DetoxAction.js' {
  declare module.exports: $Exports<'detox/src/android/espressoapi/DetoxAction'>;
}
declare module 'detox/src/android/espressoapi/DetoxMatcher.js' {
  declare module.exports: $Exports<'detox/src/android/espressoapi/DetoxMatcher'>;
}
declare module 'detox/src/android/espressoapi/ViewActions.js' {
  declare module.exports: $Exports<'detox/src/android/espressoapi/ViewActions'>;
}
declare module 'detox/src/android/expect.js' {
  declare module.exports: $Exports<'detox/src/android/expect'>;
}
declare module 'detox/src/android/matcher.js' {
  declare module.exports: $Exports<'detox/src/android/matcher'>;
}
declare module 'detox/src/artifacts/ArtifactsCopier.js' {
  declare module.exports: $Exports<'detox/src/artifacts/ArtifactsCopier'>;
}
declare module 'detox/src/artifacts/ArtifactsPathsProvider.js' {
  declare module.exports: $Exports<'detox/src/artifacts/ArtifactsPathsProvider'>;
}
declare module 'detox/src/client/actions/actions.js' {
  declare module.exports: $Exports<'detox/src/client/actions/actions'>;
}
declare module 'detox/src/client/AsyncWebSocket.js' {
  declare module.exports: $Exports<'detox/src/client/AsyncWebSocket'>;
}
declare module 'detox/src/client/Client.js' {
  declare module.exports: $Exports<'detox/src/client/Client'>;
}
declare module 'detox/src/configuration.js' {
  declare module.exports: $Exports<'detox/src/configuration'>;
}
declare module 'detox/src/configurations.mock.js' {
  declare module.exports: $Exports<'detox/src/configurations.mock'>;
}
declare module 'detox/src/Detox.js' {
  declare module.exports: $Exports<'detox/src/Detox'>;
}
declare module 'detox/src/devices/android/AAPT.js' {
  declare module.exports: $Exports<'detox/src/devices/android/AAPT'>;
}
declare module 'detox/src/devices/android/ADB.js' {
  declare module.exports: $Exports<'detox/src/devices/android/ADB'>;
}
declare module 'detox/src/devices/android/APKPath.js' {
  declare module.exports: $Exports<'detox/src/devices/android/APKPath'>;
}
declare module 'detox/src/devices/android/Emulator.js' {
  declare module.exports: $Exports<'detox/src/devices/android/Emulator'>;
}
declare module 'detox/src/devices/android/EmulatorTelnet.js' {
  declare module.exports: $Exports<'detox/src/devices/android/EmulatorTelnet'>;
}
declare module 'detox/src/devices/AndroidDriver.js' {
  declare module.exports: $Exports<'detox/src/devices/AndroidDriver'>;
}
declare module 'detox/src/devices/AppleSimUtils.js' {
  declare module.exports: $Exports<'detox/src/devices/AppleSimUtils'>;
}
declare module 'detox/src/devices/AttachedAndroidDriver.js' {
  declare module.exports: $Exports<'detox/src/devices/AttachedAndroidDriver'>;
}
declare module 'detox/src/devices/Device.js' {
  declare module.exports: $Exports<'detox/src/devices/Device'>;
}
declare module 'detox/src/devices/DeviceDriverBase.js' {
  declare module.exports: $Exports<'detox/src/devices/DeviceDriverBase'>;
}
declare module 'detox/src/devices/EmulatorDriver.js' {
  declare module.exports: $Exports<'detox/src/devices/EmulatorDriver'>;
}
declare module 'detox/src/devices/IosDriver.js' {
  declare module.exports: $Exports<'detox/src/devices/IosDriver'>;
}
declare module 'detox/src/devices/SimulatorDriver.js' {
  declare module.exports: $Exports<'detox/src/devices/SimulatorDriver'>;
}
declare module 'detox/src/errors/CustomError.js' {
  declare module.exports: $Exports<'detox/src/errors/CustomError'>;
}
declare module 'detox/src/exportWrapper.js' {
  declare module.exports: $Exports<'detox/src/exportWrapper'>;
}
declare module 'detox/src/index.js' {
  declare module.exports: $Exports<'detox/src/index'>;
}
declare module 'detox/src/invoke.js' {
  declare module.exports: $Exports<'detox/src/invoke'>;
}
declare module 'detox/src/invoke/EarlGrey.js' {
  declare module.exports: $Exports<'detox/src/invoke/EarlGrey'>;
}
declare module 'detox/src/invoke/Espresso.js' {
  declare module.exports: $Exports<'detox/src/invoke/Espresso'>;
}
declare module 'detox/src/invoke/Invoke.js' {
  declare module.exports: $Exports<'detox/src/invoke/Invoke'>;
}
declare module 'detox/src/ios/earlgreyapi/GREYActions.js' {
  declare module.exports: $Exports<'detox/src/ios/earlgreyapi/GREYActions'>;
}
declare module 'detox/src/ios/earlgreyapi/GREYConfiguration.js' {
  declare module.exports: $Exports<'detox/src/ios/earlgreyapi/GREYConfiguration'>;
}
declare module 'detox/src/ios/earlgreyapi/GREYMatchers.js' {
  declare module.exports: $Exports<'detox/src/ios/earlgreyapi/GREYMatchers'>;
}
declare module 'detox/src/ios/earlgreyapi/GREYMatchers+Detox.js' {
  declare module.exports: $Exports<'detox/src/ios/earlgreyapi/GREYMatchers+Detox'>;
}
declare module 'detox/src/ios/expect.js' {
  declare module.exports: $Exports<'detox/src/ios/expect'>;
}
declare module 'detox/src/ios/matchers.js' {
  declare module.exports: $Exports<'detox/src/ios/matchers'>;
}
declare module 'detox/src/platform.js' {
  declare module.exports: $Exports<'detox/src/platform'>;
}
declare module 'detox/src/utils/argparse.js' {
  declare module.exports: $Exports<'detox/src/utils/argparse'>;
}
declare module 'detox/src/utils/environment.js' {
  declare module.exports: $Exports<'detox/src/utils/environment'>;
}
declare module 'detox/src/utils/exec.js' {
  declare module.exports: $Exports<'detox/src/utils/exec'>;
}
declare module 'detox/src/utils/fsext.js' {
  declare module.exports: $Exports<'detox/src/utils/fsext'>;
}
declare module 'detox/src/utils/retry.js' {
  declare module.exports: $Exports<'detox/src/utils/retry'>;
}
declare module 'detox/src/utils/sh.js' {
  declare module.exports: $Exports<'detox/src/utils/sh'>;
}
declare module 'detox/src/utils/uuid.js' {
  declare module.exports: $Exports<'detox/src/utils/uuid'>;
}
declare module 'detox/wallaby.js' {
  declare module.exports: $Exports<'detox/wallaby'>;
}
