// flow-typed signature: 5fab6fadc037b333db5e1e5f39457899
// flow-typed version: <<STUB>>/detox_v^9.0.6/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'detox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'detox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'detox/local-cli/detox-build-framework-cache' {
  declare module.exports: any;
}

declare module 'detox/local-cli/detox-build' {
  declare module.exports: any;
}

declare module 'detox/local-cli/detox-clean-framework-cache' {
  declare module.exports: any;
}

declare module 'detox/local-cli/detox-init' {
  declare module.exports: any;
}

declare module 'detox/local-cli/detox-run-server' {
  declare module.exports: any;
}

declare module 'detox/local-cli/detox-test' {
  declare module.exports: any;
}

declare module 'detox/local-cli/detox' {
  declare module.exports: any;
}

declare module 'detox/local-cli/templates/firstTestContent' {
  declare module.exports: any;
}

declare module 'detox/local-cli/templates/jest' {
  declare module.exports: any;
}

declare module 'detox/local-cli/templates/mocha' {
  declare module.exports: any;
}

declare module 'detox/runners/jest/adapter' {
  declare module.exports: any;
}

declare module 'detox/runners/jest/DetoxJestAdapter' {
  declare module.exports: any;
}

declare module 'detox/runners/mocha/adapter' {
  declare module.exports: any;
}

declare module 'detox/runners/mocha/DetoxMochaAdapter' {
  declare module.exports: any;
}

declare module 'detox/scripts/build' {
  declare module.exports: any;
}

declare module 'detox/scripts/postinstall' {
  declare module.exports: any;
}

declare module 'detox/src/android/espressoapi/Detox' {
  declare module.exports: any;
}

declare module 'detox/src/android/espressoapi/DetoxAction' {
  declare module.exports: any;
}

declare module 'detox/src/android/espressoapi/DetoxMatcher' {
  declare module.exports: any;
}

declare module 'detox/src/android/espressoapi/EspressoDetox' {
  declare module.exports: any;
}

declare module 'detox/src/android/espressoapi/UIAutomator' {
  declare module.exports: any;
}

declare module 'detox/src/android/espressoapi/UIDevice' {
  declare module.exports: any;
}

declare module 'detox/src/android/espressoapi/ViewActions' {
  declare module.exports: any;
}

declare module 'detox/src/android/expect' {
  declare module.exports: any;
}

declare module 'detox/src/android/matcher' {
  declare module.exports: any;
}

declare module 'detox/src/artifacts/ArtifactsManager' {
  declare module.exports: any;
}

declare module 'detox/src/artifacts/log/android/ADBLogcatPlugin' {
  declare module.exports: any;
}

declare module 'detox/src/artifacts/log/android/ADBLogcatRecording' {
  declare module.exports: any;
}

declare module 'detox/src/artifacts/log/ios/SimulatorLogPlugin' {
  declare module.exports: any;
}

declare module 'detox/src/artifacts/log/ios/SimulatorLogRecording' {
  declare module.exports: any;
}

declare module 'detox/src/artifacts/log/LogArtifactPlugin' {
  declare module.exports: any;
}

declare module 'detox/src/artifacts/screenshot/ADBScreencapPlugin' {
  declare module.exports: any;
}

declare module 'detox/src/artifacts/screenshot/ScreenshotArtifactPlugin' {
  declare module.exports: any;
}

declare module 'detox/src/artifacts/screenshot/SimulatorScreenshotPlugin' {
  declare module.exports: any;
}

declare module 'detox/src/artifacts/templates/artifact/Artifact' {
  declare module.exports: any;
}

declare module 'detox/src/artifacts/templates/plugin/__mocks__/ArtifactsApi.mock' {
  declare module.exports: any;
}

declare module 'detox/src/artifacts/templates/plugin/__mocks__/testSummaries.mock' {
  declare module.exports: any;
}

declare module 'detox/src/artifacts/templates/plugin/ArtifactPlugin' {
  declare module.exports: any;
}

declare module 'detox/src/artifacts/templates/plugin/StartupAndTestRecorderPlugin' {
  declare module.exports: any;
}

declare module 'detox/src/artifacts/templates/plugin/TwoSnapshotsPerTestPlugin' {
  declare module.exports: any;
}

declare module 'detox/src/artifacts/templates/plugin/WholeTestRecorderPlugin' {
  declare module.exports: any;
}

declare module 'detox/src/artifacts/utils/AndroidDevicePathBuilder' {
  declare module.exports: any;
}

declare module 'detox/src/artifacts/utils/ArtifactPathBuilder' {
  declare module.exports: any;
}

declare module 'detox/src/artifacts/utils/buildDefaultArtifactsRootDirpath' {
  declare module.exports: any;
}

declare module 'detox/src/artifacts/utils/getTimeStampString' {
  declare module.exports: any;
}

declare module 'detox/src/artifacts/video/ADBScreenrecorderArtifact' {
  declare module.exports: any;
}

declare module 'detox/src/artifacts/video/ADBScreenrecorderPlugin' {
  declare module.exports: any;
}

declare module 'detox/src/artifacts/video/SimulatorRecordVideoPlugin' {
  declare module.exports: any;
}

declare module 'detox/src/artifacts/video/VideoArtifactPlugin' {
  declare module.exports: any;
}

declare module 'detox/src/client/actions/actions' {
  declare module.exports: any;
}

declare module 'detox/src/client/AsyncWebSocket' {
  declare module.exports: any;
}

declare module 'detox/src/client/Client' {
  declare module.exports: any;
}

declare module 'detox/src/client/DetoxError' {
  declare module.exports: any;
}

declare module 'detox/src/configuration' {
  declare module.exports: any;
}

declare module 'detox/src/configurations.mock' {
  declare module.exports: any;
}

declare module 'detox/src/Detox' {
  declare module.exports: any;
}

declare module 'detox/src/DetoxConstants' {
  declare module.exports: any;
}

declare module 'detox/src/devices/android/AAPT' {
  declare module.exports: any;
}

declare module 'detox/src/devices/android/ADB' {
  declare module.exports: any;
}

declare module 'detox/src/devices/android/APKPath' {
  declare module.exports: any;
}

declare module 'detox/src/devices/android/Emulator' {
  declare module.exports: any;
}

declare module 'detox/src/devices/android/EmulatorTelnet' {
  declare module.exports: any;
}

declare module 'detox/src/devices/Device' {
  declare module.exports: any;
}

declare module 'detox/src/devices/DeviceRegistry' {
  declare module.exports: any;
}

declare module 'detox/src/devices/drivers/AndroidDriver' {
  declare module.exports: any;
}

declare module 'detox/src/devices/drivers/AttachedAndroidDriver' {
  declare module.exports: any;
}

declare module 'detox/src/devices/drivers/DeviceDriverBase' {
  declare module.exports: any;
}

declare module 'detox/src/devices/drivers/EmulatorDriver' {
  declare module.exports: any;
}

declare module 'detox/src/devices/drivers/IosDriver' {
  declare module.exports: any;
}

declare module 'detox/src/devices/drivers/SimulatorDriver' {
  declare module.exports: any;
}

declare module 'detox/src/devices/ios/AppleSimUtils' {
  declare module.exports: any;
}

declare module 'detox/src/errors/CustomError' {
  declare module.exports: any;
}

declare module 'detox/src/errors/DetoxChildProcessError' {
  declare module.exports: any;
}

declare module 'detox/src/errors/DetoxConfigError' {
  declare module.exports: any;
}

declare module 'detox/src/errors/DetoxRuntimeError' {
  declare module.exports: any;
}

declare module 'detox/src/exportWrapper' {
  declare module.exports: any;
}

declare module 'detox/src/index' {
  declare module.exports: any;
}

declare module 'detox/src/invoke' {
  declare module.exports: any;
}

declare module 'detox/src/invoke/EarlGrey' {
  declare module.exports: any;
}

declare module 'detox/src/invoke/Espresso' {
  declare module.exports: any;
}

declare module 'detox/src/invoke/Invoke' {
  declare module.exports: any;
}

declare module 'detox/src/ios/earlgreyapi/EarlGreyImpl' {
  declare module.exports: any;
}

declare module 'detox/src/ios/earlgreyapi/GREYActions' {
  declare module.exports: any;
}

declare module 'detox/src/ios/earlgreyapi/GREYCondition' {
  declare module.exports: any;
}

declare module 'detox/src/ios/earlgreyapi/GREYConditionDetox' {
  declare module.exports: any;
}

declare module 'detox/src/ios/earlgreyapi/GREYConfiguration' {
  declare module.exports: any;
}

declare module 'detox/src/ios/earlgreyapi/GREYConfigurationDetox' {
  declare module.exports: any;
}

declare module 'detox/src/ios/earlgreyapi/GREYInteraction' {
  declare module.exports: any;
}

declare module 'detox/src/ios/earlgreyapi/GREYMatchers' {
  declare module.exports: any;
}

declare module 'detox/src/ios/earlgreyapi/GREYMatchers+Detox' {
  declare module.exports: any;
}

declare module 'detox/src/ios/expect' {
  declare module.exports: any;
}

declare module 'detox/src/ios/matchers' {
  declare module.exports: any;
}

declare module 'detox/src/platform' {
  declare module.exports: any;
}

declare module 'detox/src/server/DetoxServer' {
  declare module.exports: any;
}

declare module 'detox/src/utils/__mocks__/logger' {
  declare module.exports: any;
}

declare module 'detox/src/utils/appdatapath' {
  declare module.exports: any;
}

declare module 'detox/src/utils/argparse' {
  declare module.exports: any;
}

declare module 'detox/src/utils/AsyncEmitter' {
  declare module.exports: any;
}

declare module 'detox/src/utils/constructSafeFilename' {
  declare module.exports: any;
}

declare module 'detox/src/utils/debug' {
  declare module.exports: any;
}

declare module 'detox/src/utils/environment' {
  declare module.exports: any;
}

declare module 'detox/src/utils/exec' {
  declare module.exports: any;
}

declare module 'detox/src/utils/fsext' {
  declare module.exports: any;
}

declare module 'detox/src/utils/logger' {
  declare module.exports: any;
}

declare module 'detox/src/utils/pipeCommands' {
  declare module.exports: any;
}

declare module 'detox/src/utils/retry' {
  declare module.exports: any;
}

declare module 'detox/src/utils/sh' {
  declare module.exports: any;
}

declare module 'detox/src/utils/sleep' {
  declare module.exports: any;
}

declare module 'detox/src/utils/string' {
  declare module.exports: any;
}

declare module 'detox/src/utils/uuid' {
  declare module.exports: any;
}

declare module 'detox/wallaby' {
  declare module.exports: any;
}

// Filename aliases
declare module 'detox/local-cli/detox-build-framework-cache.js' {
  declare module.exports: $Exports<'detox/local-cli/detox-build-framework-cache'>;
}
declare module 'detox/local-cli/detox-build.js' {
  declare module.exports: $Exports<'detox/local-cli/detox-build'>;
}
declare module 'detox/local-cli/detox-clean-framework-cache.js' {
  declare module.exports: $Exports<'detox/local-cli/detox-clean-framework-cache'>;
}
declare module 'detox/local-cli/detox-init.js' {
  declare module.exports: $Exports<'detox/local-cli/detox-init'>;
}
declare module 'detox/local-cli/detox-run-server.js' {
  declare module.exports: $Exports<'detox/local-cli/detox-run-server'>;
}
declare module 'detox/local-cli/detox-test.js' {
  declare module.exports: $Exports<'detox/local-cli/detox-test'>;
}
declare module 'detox/local-cli/detox.js' {
  declare module.exports: $Exports<'detox/local-cli/detox'>;
}
declare module 'detox/local-cli/templates/firstTestContent.js' {
  declare module.exports: $Exports<'detox/local-cli/templates/firstTestContent'>;
}
declare module 'detox/local-cli/templates/jest.js' {
  declare module.exports: $Exports<'detox/local-cli/templates/jest'>;
}
declare module 'detox/local-cli/templates/mocha.js' {
  declare module.exports: $Exports<'detox/local-cli/templates/mocha'>;
}
declare module 'detox/runners/jest/adapter.js' {
  declare module.exports: $Exports<'detox/runners/jest/adapter'>;
}
declare module 'detox/runners/jest/DetoxJestAdapter.js' {
  declare module.exports: $Exports<'detox/runners/jest/DetoxJestAdapter'>;
}
declare module 'detox/runners/mocha/adapter.js' {
  declare module.exports: $Exports<'detox/runners/mocha/adapter'>;
}
declare module 'detox/runners/mocha/DetoxMochaAdapter.js' {
  declare module.exports: $Exports<'detox/runners/mocha/DetoxMochaAdapter'>;
}
declare module 'detox/scripts/build.js' {
  declare module.exports: $Exports<'detox/scripts/build'>;
}
declare module 'detox/scripts/postinstall.js' {
  declare module.exports: $Exports<'detox/scripts/postinstall'>;
}
declare module 'detox/src/android/espressoapi/Detox.js' {
  declare module.exports: $Exports<'detox/src/android/espressoapi/Detox'>;
}
declare module 'detox/src/android/espressoapi/DetoxAction.js' {
  declare module.exports: $Exports<'detox/src/android/espressoapi/DetoxAction'>;
}
declare module 'detox/src/android/espressoapi/DetoxMatcher.js' {
  declare module.exports: $Exports<'detox/src/android/espressoapi/DetoxMatcher'>;
}
declare module 'detox/src/android/espressoapi/EspressoDetox.js' {
  declare module.exports: $Exports<'detox/src/android/espressoapi/EspressoDetox'>;
}
declare module 'detox/src/android/espressoapi/UIAutomator.js' {
  declare module.exports: $Exports<'detox/src/android/espressoapi/UIAutomator'>;
}
declare module 'detox/src/android/espressoapi/UIDevice.js' {
  declare module.exports: $Exports<'detox/src/android/espressoapi/UIDevice'>;
}
declare module 'detox/src/android/espressoapi/ViewActions.js' {
  declare module.exports: $Exports<'detox/src/android/espressoapi/ViewActions'>;
}
declare module 'detox/src/android/expect.js' {
  declare module.exports: $Exports<'detox/src/android/expect'>;
}
declare module 'detox/src/android/matcher.js' {
  declare module.exports: $Exports<'detox/src/android/matcher'>;
}
declare module 'detox/src/artifacts/ArtifactsManager.js' {
  declare module.exports: $Exports<'detox/src/artifacts/ArtifactsManager'>;
}
declare module 'detox/src/artifacts/log/android/ADBLogcatPlugin.js' {
  declare module.exports: $Exports<'detox/src/artifacts/log/android/ADBLogcatPlugin'>;
}
declare module 'detox/src/artifacts/log/android/ADBLogcatRecording.js' {
  declare module.exports: $Exports<'detox/src/artifacts/log/android/ADBLogcatRecording'>;
}
declare module 'detox/src/artifacts/log/ios/SimulatorLogPlugin.js' {
  declare module.exports: $Exports<'detox/src/artifacts/log/ios/SimulatorLogPlugin'>;
}
declare module 'detox/src/artifacts/log/ios/SimulatorLogRecording.js' {
  declare module.exports: $Exports<'detox/src/artifacts/log/ios/SimulatorLogRecording'>;
}
declare module 'detox/src/artifacts/log/LogArtifactPlugin.js' {
  declare module.exports: $Exports<'detox/src/artifacts/log/LogArtifactPlugin'>;
}
declare module 'detox/src/artifacts/screenshot/ADBScreencapPlugin.js' {
  declare module.exports: $Exports<'detox/src/artifacts/screenshot/ADBScreencapPlugin'>;
}
declare module 'detox/src/artifacts/screenshot/ScreenshotArtifactPlugin.js' {
  declare module.exports: $Exports<'detox/src/artifacts/screenshot/ScreenshotArtifactPlugin'>;
}
declare module 'detox/src/artifacts/screenshot/SimulatorScreenshotPlugin.js' {
  declare module.exports: $Exports<'detox/src/artifacts/screenshot/SimulatorScreenshotPlugin'>;
}
declare module 'detox/src/artifacts/templates/artifact/Artifact.js' {
  declare module.exports: $Exports<'detox/src/artifacts/templates/artifact/Artifact'>;
}
declare module 'detox/src/artifacts/templates/plugin/__mocks__/ArtifactsApi.mock.js' {
  declare module.exports: $Exports<'detox/src/artifacts/templates/plugin/__mocks__/ArtifactsApi.mock'>;
}
declare module 'detox/src/artifacts/templates/plugin/__mocks__/testSummaries.mock.js' {
  declare module.exports: $Exports<'detox/src/artifacts/templates/plugin/__mocks__/testSummaries.mock'>;
}
declare module 'detox/src/artifacts/templates/plugin/ArtifactPlugin.js' {
  declare module.exports: $Exports<'detox/src/artifacts/templates/plugin/ArtifactPlugin'>;
}
declare module 'detox/src/artifacts/templates/plugin/StartupAndTestRecorderPlugin.js' {
  declare module.exports: $Exports<'detox/src/artifacts/templates/plugin/StartupAndTestRecorderPlugin'>;
}
declare module 'detox/src/artifacts/templates/plugin/TwoSnapshotsPerTestPlugin.js' {
  declare module.exports: $Exports<'detox/src/artifacts/templates/plugin/TwoSnapshotsPerTestPlugin'>;
}
declare module 'detox/src/artifacts/templates/plugin/WholeTestRecorderPlugin.js' {
  declare module.exports: $Exports<'detox/src/artifacts/templates/plugin/WholeTestRecorderPlugin'>;
}
declare module 'detox/src/artifacts/utils/AndroidDevicePathBuilder.js' {
  declare module.exports: $Exports<'detox/src/artifacts/utils/AndroidDevicePathBuilder'>;
}
declare module 'detox/src/artifacts/utils/ArtifactPathBuilder.js' {
  declare module.exports: $Exports<'detox/src/artifacts/utils/ArtifactPathBuilder'>;
}
declare module 'detox/src/artifacts/utils/buildDefaultArtifactsRootDirpath.js' {
  declare module.exports: $Exports<'detox/src/artifacts/utils/buildDefaultArtifactsRootDirpath'>;
}
declare module 'detox/src/artifacts/utils/getTimeStampString.js' {
  declare module.exports: $Exports<'detox/src/artifacts/utils/getTimeStampString'>;
}
declare module 'detox/src/artifacts/video/ADBScreenrecorderArtifact.js' {
  declare module.exports: $Exports<'detox/src/artifacts/video/ADBScreenrecorderArtifact'>;
}
declare module 'detox/src/artifacts/video/ADBScreenrecorderPlugin.js' {
  declare module.exports: $Exports<'detox/src/artifacts/video/ADBScreenrecorderPlugin'>;
}
declare module 'detox/src/artifacts/video/SimulatorRecordVideoPlugin.js' {
  declare module.exports: $Exports<'detox/src/artifacts/video/SimulatorRecordVideoPlugin'>;
}
declare module 'detox/src/artifacts/video/VideoArtifactPlugin.js' {
  declare module.exports: $Exports<'detox/src/artifacts/video/VideoArtifactPlugin'>;
}
declare module 'detox/src/client/actions/actions.js' {
  declare module.exports: $Exports<'detox/src/client/actions/actions'>;
}
declare module 'detox/src/client/AsyncWebSocket.js' {
  declare module.exports: $Exports<'detox/src/client/AsyncWebSocket'>;
}
declare module 'detox/src/client/Client.js' {
  declare module.exports: $Exports<'detox/src/client/Client'>;
}
declare module 'detox/src/client/DetoxError.js' {
  declare module.exports: $Exports<'detox/src/client/DetoxError'>;
}
declare module 'detox/src/configuration.js' {
  declare module.exports: $Exports<'detox/src/configuration'>;
}
declare module 'detox/src/configurations.mock.js' {
  declare module.exports: $Exports<'detox/src/configurations.mock'>;
}
declare module 'detox/src/Detox.js' {
  declare module.exports: $Exports<'detox/src/Detox'>;
}
declare module 'detox/src/DetoxConstants.js' {
  declare module.exports: $Exports<'detox/src/DetoxConstants'>;
}
declare module 'detox/src/devices/android/AAPT.js' {
  declare module.exports: $Exports<'detox/src/devices/android/AAPT'>;
}
declare module 'detox/src/devices/android/ADB.js' {
  declare module.exports: $Exports<'detox/src/devices/android/ADB'>;
}
declare module 'detox/src/devices/android/APKPath.js' {
  declare module.exports: $Exports<'detox/src/devices/android/APKPath'>;
}
declare module 'detox/src/devices/android/Emulator.js' {
  declare module.exports: $Exports<'detox/src/devices/android/Emulator'>;
}
declare module 'detox/src/devices/android/EmulatorTelnet.js' {
  declare module.exports: $Exports<'detox/src/devices/android/EmulatorTelnet'>;
}
declare module 'detox/src/devices/Device.js' {
  declare module.exports: $Exports<'detox/src/devices/Device'>;
}
declare module 'detox/src/devices/DeviceRegistry.js' {
  declare module.exports: $Exports<'detox/src/devices/DeviceRegistry'>;
}
declare module 'detox/src/devices/drivers/AndroidDriver.js' {
  declare module.exports: $Exports<'detox/src/devices/drivers/AndroidDriver'>;
}
declare module 'detox/src/devices/drivers/AttachedAndroidDriver.js' {
  declare module.exports: $Exports<'detox/src/devices/drivers/AttachedAndroidDriver'>;
}
declare module 'detox/src/devices/drivers/DeviceDriverBase.js' {
  declare module.exports: $Exports<'detox/src/devices/drivers/DeviceDriverBase'>;
}
declare module 'detox/src/devices/drivers/EmulatorDriver.js' {
  declare module.exports: $Exports<'detox/src/devices/drivers/EmulatorDriver'>;
}
declare module 'detox/src/devices/drivers/IosDriver.js' {
  declare module.exports: $Exports<'detox/src/devices/drivers/IosDriver'>;
}
declare module 'detox/src/devices/drivers/SimulatorDriver.js' {
  declare module.exports: $Exports<'detox/src/devices/drivers/SimulatorDriver'>;
}
declare module 'detox/src/devices/ios/AppleSimUtils.js' {
  declare module.exports: $Exports<'detox/src/devices/ios/AppleSimUtils'>;
}
declare module 'detox/src/errors/CustomError.js' {
  declare module.exports: $Exports<'detox/src/errors/CustomError'>;
}
declare module 'detox/src/errors/DetoxChildProcessError.js' {
  declare module.exports: $Exports<'detox/src/errors/DetoxChildProcessError'>;
}
declare module 'detox/src/errors/DetoxConfigError.js' {
  declare module.exports: $Exports<'detox/src/errors/DetoxConfigError'>;
}
declare module 'detox/src/errors/DetoxRuntimeError.js' {
  declare module.exports: $Exports<'detox/src/errors/DetoxRuntimeError'>;
}
declare module 'detox/src/exportWrapper.js' {
  declare module.exports: $Exports<'detox/src/exportWrapper'>;
}
declare module 'detox/src/index.js' {
  declare module.exports: $Exports<'detox/src/index'>;
}
declare module 'detox/src/invoke.js' {
  declare module.exports: $Exports<'detox/src/invoke'>;
}
declare module 'detox/src/invoke/EarlGrey.js' {
  declare module.exports: $Exports<'detox/src/invoke/EarlGrey'>;
}
declare module 'detox/src/invoke/Espresso.js' {
  declare module.exports: $Exports<'detox/src/invoke/Espresso'>;
}
declare module 'detox/src/invoke/Invoke.js' {
  declare module.exports: $Exports<'detox/src/invoke/Invoke'>;
}
declare module 'detox/src/ios/earlgreyapi/EarlGreyImpl.js' {
  declare module.exports: $Exports<'detox/src/ios/earlgreyapi/EarlGreyImpl'>;
}
declare module 'detox/src/ios/earlgreyapi/GREYActions.js' {
  declare module.exports: $Exports<'detox/src/ios/earlgreyapi/GREYActions'>;
}
declare module 'detox/src/ios/earlgreyapi/GREYCondition.js' {
  declare module.exports: $Exports<'detox/src/ios/earlgreyapi/GREYCondition'>;
}
declare module 'detox/src/ios/earlgreyapi/GREYConditionDetox.js' {
  declare module.exports: $Exports<'detox/src/ios/earlgreyapi/GREYConditionDetox'>;
}
declare module 'detox/src/ios/earlgreyapi/GREYConfiguration.js' {
  declare module.exports: $Exports<'detox/src/ios/earlgreyapi/GREYConfiguration'>;
}
declare module 'detox/src/ios/earlgreyapi/GREYConfigurationDetox.js' {
  declare module.exports: $Exports<'detox/src/ios/earlgreyapi/GREYConfigurationDetox'>;
}
declare module 'detox/src/ios/earlgreyapi/GREYInteraction.js' {
  declare module.exports: $Exports<'detox/src/ios/earlgreyapi/GREYInteraction'>;
}
declare module 'detox/src/ios/earlgreyapi/GREYMatchers.js' {
  declare module.exports: $Exports<'detox/src/ios/earlgreyapi/GREYMatchers'>;
}
declare module 'detox/src/ios/earlgreyapi/GREYMatchers+Detox.js' {
  declare module.exports: $Exports<'detox/src/ios/earlgreyapi/GREYMatchers+Detox'>;
}
declare module 'detox/src/ios/expect.js' {
  declare module.exports: $Exports<'detox/src/ios/expect'>;
}
declare module 'detox/src/ios/matchers.js' {
  declare module.exports: $Exports<'detox/src/ios/matchers'>;
}
declare module 'detox/src/platform.js' {
  declare module.exports: $Exports<'detox/src/platform'>;
}
declare module 'detox/src/server/DetoxServer.js' {
  declare module.exports: $Exports<'detox/src/server/DetoxServer'>;
}
declare module 'detox/src/utils/__mocks__/logger.js' {
  declare module.exports: $Exports<'detox/src/utils/__mocks__/logger'>;
}
declare module 'detox/src/utils/appdatapath.js' {
  declare module.exports: $Exports<'detox/src/utils/appdatapath'>;
}
declare module 'detox/src/utils/argparse.js' {
  declare module.exports: $Exports<'detox/src/utils/argparse'>;
}
declare module 'detox/src/utils/AsyncEmitter.js' {
  declare module.exports: $Exports<'detox/src/utils/AsyncEmitter'>;
}
declare module 'detox/src/utils/constructSafeFilename.js' {
  declare module.exports: $Exports<'detox/src/utils/constructSafeFilename'>;
}
declare module 'detox/src/utils/debug.js' {
  declare module.exports: $Exports<'detox/src/utils/debug'>;
}
declare module 'detox/src/utils/environment.js' {
  declare module.exports: $Exports<'detox/src/utils/environment'>;
}
declare module 'detox/src/utils/exec.js' {
  declare module.exports: $Exports<'detox/src/utils/exec'>;
}
declare module 'detox/src/utils/fsext.js' {
  declare module.exports: $Exports<'detox/src/utils/fsext'>;
}
declare module 'detox/src/utils/logger.js' {
  declare module.exports: $Exports<'detox/src/utils/logger'>;
}
declare module 'detox/src/utils/pipeCommands.js' {
  declare module.exports: $Exports<'detox/src/utils/pipeCommands'>;
}
declare module 'detox/src/utils/retry.js' {
  declare module.exports: $Exports<'detox/src/utils/retry'>;
}
declare module 'detox/src/utils/sh.js' {
  declare module.exports: $Exports<'detox/src/utils/sh'>;
}
declare module 'detox/src/utils/sleep.js' {
  declare module.exports: $Exports<'detox/src/utils/sleep'>;
}
declare module 'detox/src/utils/string.js' {
  declare module.exports: $Exports<'detox/src/utils/string'>;
}
declare module 'detox/src/utils/uuid.js' {
  declare module.exports: $Exports<'detox/src/utils/uuid'>;
}
declare module 'detox/wallaby.js' {
  declare module.exports: $Exports<'detox/wallaby'>;
}
