// flow-typed signature: 118865d8e450781ec62500f7159c1427
// flow-typed version: <<STUB>>/entities_v^1.1.1/flow_v0.63.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'entities'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'entities' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'entities/lib/decode_codepoint' {
  declare module.exports: any;
}

declare module 'entities/lib/decode' {
  declare module.exports: any;
}

declare module 'entities/lib/encode' {
  declare module.exports: any;
}

declare module 'entities/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'entities/index' {
  declare module.exports: $Exports<'entities'>;
}
declare module 'entities/index.js' {
  declare module.exports: $Exports<'entities'>;
}
declare module 'entities/lib/decode_codepoint.js' {
  declare module.exports: $Exports<'entities/lib/decode_codepoint'>;
}
declare module 'entities/lib/decode.js' {
  declare module.exports: $Exports<'entities/lib/decode'>;
}
declare module 'entities/lib/encode.js' {
  declare module.exports: $Exports<'entities/lib/encode'>;
}
declare module 'entities/test/test.js' {
  declare module.exports: $Exports<'entities/test/test'>;
}
