// flow-typed signature: cd06b23edbe92711c0399ab23744dfc5
// flow-typed version: <<STUB>>/eslint-plugin-spellcheck_v0.0.14/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-spellcheck'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-spellcheck' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-spellcheck/rules/spell-checker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-spellcheck/index' {
  declare module.exports: $Exports<'eslint-plugin-spellcheck'>;
}
declare module 'eslint-plugin-spellcheck/index.js' {
  declare module.exports: $Exports<'eslint-plugin-spellcheck'>;
}
declare module 'eslint-plugin-spellcheck/rules/spell-checker.js' {
  declare module.exports: $Exports<'eslint-plugin-spellcheck/rules/spell-checker'>;
}
