// flow-typed signature: bdd6d740ed1472fde8ecf483ba589452
// flow-typed version: <<STUB>>/expo-application_v2.1.0/flow_v0.92.0

/**
 * Flowtype definitions for Application
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.10.0
 */
declare module 'expo-application' {
  declare export var nativeApplicationVersion: string | null;
  declare export var nativeBuildVersion: string | null;
  declare export var applicationName: string | null;
  declare export var applicationId: string | null;
  declare export var androidId: string | null;
  declare export function getInstallReferrerAsync(): Promise<string>;
  declare export function getIosIdForVendorAsync(): Promise<string>;

  declare export var ApplicationReleaseType: {|
    +UNKNOWN: 0, // 0
    +SIMULATOR: 1, // 1
    +ENTERPRISE: 2, // 2
    +DEVELOPMENT: 3, // 3
    +AD_HOC: 4, // 4
    +APP_STORE: 5, // 5
  |};
  declare export function getIosApplicationReleaseTypeAsync(): Promise<$Values<typeof ApplicationReleaseType>, >;
  declare export function getIosPushNotificationServiceEnvironmentAsync(): Promise<string>;
  declare export function getInstallationTimeAsync(): Promise<Date>;
  declare export function getLastUpdateTimeAsync(): Promise<Date>;
}
