// flow-typed signature: 9a2a513d09f22bca8303f3a649d9a7f4
// flow-typed version: <<STUB>>/htmlparser2_v^3.9.2/flow_v0.63.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'htmlparser2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'htmlparser2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'htmlparser2/lib/CollectingHandler' {
  declare module.exports: any;
}

declare module 'htmlparser2/lib/FeedHandler' {
  declare module.exports: any;
}

declare module 'htmlparser2/lib/index' {
  declare module.exports: any;
}

declare module 'htmlparser2/lib/Parser' {
  declare module.exports: any;
}

declare module 'htmlparser2/lib/ProxyHandler' {
  declare module.exports: any;
}

declare module 'htmlparser2/lib/Stream' {
  declare module.exports: any;
}

declare module 'htmlparser2/lib/Tokenizer' {
  declare module.exports: any;
}

declare module 'htmlparser2/lib/WritableStream' {
  declare module.exports: any;
}

// Filename aliases
declare module 'htmlparser2/lib/CollectingHandler.js' {
  declare module.exports: $Exports<'htmlparser2/lib/CollectingHandler'>;
}
declare module 'htmlparser2/lib/FeedHandler.js' {
  declare module.exports: $Exports<'htmlparser2/lib/FeedHandler'>;
}
declare module 'htmlparser2/lib/index.js' {
  declare module.exports: $Exports<'htmlparser2/lib/index'>;
}
declare module 'htmlparser2/lib/Parser.js' {
  declare module.exports: $Exports<'htmlparser2/lib/Parser'>;
}
declare module 'htmlparser2/lib/ProxyHandler.js' {
  declare module.exports: $Exports<'htmlparser2/lib/ProxyHandler'>;
}
declare module 'htmlparser2/lib/Stream.js' {
  declare module.exports: $Exports<'htmlparser2/lib/Stream'>;
}
declare module 'htmlparser2/lib/Tokenizer.js' {
  declare module.exports: $Exports<'htmlparser2/lib/Tokenizer'>;
}
declare module 'htmlparser2/lib/WritableStream.js' {
  declare module.exports: $Exports<'htmlparser2/lib/WritableStream'>;
}
