// flow-typed signature: 2bc77fee31f92b09069e119905584240
// flow-typed version: <<STUB>>/jest-environment-jsdom-global_v^1.2.0/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-environment-jsdom-global'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-environment-jsdom-global' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-environment-jsdom-global/__tests__/tests' {
  declare module.exports: any;
}

declare module 'jest-environment-jsdom-global/environment' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-environment-jsdom-global/__tests__/tests.js' {
  declare module.exports: $Exports<'jest-environment-jsdom-global/__tests__/tests'>;
}
declare module 'jest-environment-jsdom-global/environment.js' {
  declare module.exports: $Exports<'jest-environment-jsdom-global/environment'>;
}
