// flow-typed signature: c231207a41c571ad115b78f973d31b28
// flow-typed version: <<STUB>>/lodash.union_v^4.6.0/flow_v0.67.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.union'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.union' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.union/index' {
  declare module.exports: $Exports<'lodash.union'>;
}
declare module 'lodash.union/index.js' {
  declare module.exports: $Exports<'lodash.union'>;
}
