// flow-typed signature: c83628737351ff464fc4ea705c3afc2a
// flow-typed version: <<STUB>>/lodash.escape_v^4.0.1/flow_v0.67.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.escape'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.escape' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.escape/index' {
  declare module.exports: $Exports<'lodash.escape'>;
}
declare module 'lodash.escape/index.js' {
  declare module.exports: $Exports<'lodash.escape'>;
}
