// flow-typed signature: 90886f4f24a461af604388c2bc3c45b1
// flow-typed version: <<STUB>>/lodash.unescape_v^4.0.1/flow_v0.67.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.unescape'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.unescape' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.unescape/index' {
  declare module.exports: $Exports<'lodash.unescape'>;
}
declare module 'lodash.unescape/index.js' {
  declare module.exports: $Exports<'lodash.unescape'>;
}
