// flow-typed signature: 09b063b7f9f08b8e9022453db373cb6d
// flow-typed version: <<STUB>>/lodash.escape_v^4.0.1/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.escape'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.escape' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.escape/index' {
  declare module.exports: $Exports<'lodash.escape'>;
}
declare module 'lodash.escape/index.js' {
  declare module.exports: $Exports<'lodash.escape'>;
}
