// flow-typed signature: 30570598634ecdc38195540df19f3205
// flow-typed version: <<STUB>>/react-native-safari-view_v2.0.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-safari-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-safari-view' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-safari-view/SafariViewManager.android' {
  declare module.exports: any;
}

declare module 'react-native-safari-view/SafariViewManager.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-safari-view/index' {
  declare module.exports: $Exports<'react-native-safari-view'>;
}
declare module 'react-native-safari-view/index.js' {
  declare module.exports: $Exports<'react-native-safari-view'>;
}
declare module 'react-native-safari-view/SafariViewManager.android.js' {
  declare module.exports: $Exports<'react-native-safari-view/SafariViewManager.android'>;
}
declare module 'react-native-safari-view/SafariViewManager.ios.js' {
  declare module.exports: $Exports<'react-native-safari-view/SafariViewManager.ios'>;
}
