// flow-typed signature: 5e3269258428f501cfac805a062f0d2a
// flow-typed version: <<STUB>>/react-native-sentry_v^0.37.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-sentry'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-sentry' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-sentry/lib/NativeClient' {
  declare module.exports: any;
}

declare module 'react-native-sentry/lib/raven-plugin' {
  declare module.exports: any;
}

declare module 'react-native-sentry/lib/RavenClient' {
  declare module.exports: any;
}

declare module 'react-native-sentry/lib/Sentry' {
  declare module.exports: any;
}

declare module 'react-native-sentry/scripts/version-bump' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-sentry/index' {
  declare module.exports: $Exports<'react-native-sentry'>;
}
declare module 'react-native-sentry/index.js' {
  declare module.exports: $Exports<'react-native-sentry'>;
}
declare module 'react-native-sentry/lib/NativeClient.js' {
  declare module.exports: $Exports<'react-native-sentry/lib/NativeClient'>;
}
declare module 'react-native-sentry/lib/raven-plugin.js' {
  declare module.exports: $Exports<'react-native-sentry/lib/raven-plugin'>;
}
declare module 'react-native-sentry/lib/RavenClient.js' {
  declare module.exports: $Exports<'react-native-sentry/lib/RavenClient'>;
}
declare module 'react-native-sentry/lib/Sentry.js' {
  declare module.exports: $Exports<'react-native-sentry/lib/Sentry'>;
}
declare module 'react-native-sentry/scripts/version-bump.js' {
  declare module.exports: $Exports<'react-native-sentry/scripts/version-bump'>;
}
