// flow-typed signature: 485014ce66b1c83183be89813a34f3a0
// flow-typed version: <<STUB>>/react-native-text-input-reset_v^1.0.2/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-text-input-reset'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-text-input-reset' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-text-input-reset/index' {
  declare module.exports: $Exports<'react-native-text-input-reset'>;
}
declare module 'react-native-text-input-reset/index.js' {
  declare module.exports: $Exports<'react-native-text-input-reset'>;
}
