// flow-typed signature: e2e477bef26c85f172d7db654ded0a2e
// flow-typed version: <<STUB>>/react-native-paper_v4.8.1/flow_v0.128.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-paper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-paper' {
  declare module.exports: any;
}
