// flow-typed signature: dfc7402db0e7f0391924710124f063fe
// flow-typed version: <<STUB>>/react-native-orientation_v^3.1.3/flow_v0.67.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-orientation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-orientation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-orientation/demo/__tests__/index.android' {
  declare module.exports: any;
}

declare module 'react-native-orientation/demo/__tests__/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-orientation/demo/app' {
  declare module.exports: any;
}

declare module 'react-native-orientation/demo/index.android' {
  declare module.exports: any;
}

declare module 'react-native-orientation/demo/index.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-orientation/demo/__tests__/index.android.js' {
  declare module.exports: $Exports<'react-native-orientation/demo/__tests__/index.android'>;
}
declare module 'react-native-orientation/demo/__tests__/index.ios.js' {
  declare module.exports: $Exports<'react-native-orientation/demo/__tests__/index.ios'>;
}
declare module 'react-native-orientation/demo/app.js' {
  declare module.exports: $Exports<'react-native-orientation/demo/app'>;
}
declare module 'react-native-orientation/demo/index.android.js' {
  declare module.exports: $Exports<'react-native-orientation/demo/index.android'>;
}
declare module 'react-native-orientation/demo/index.ios.js' {
  declare module.exports: $Exports<'react-native-orientation/demo/index.ios'>;
}
declare module 'react-native-orientation/index' {
  declare module.exports: $Exports<'react-native-orientation'>;
}
declare module 'react-native-orientation/index.js' {
  declare module.exports: $Exports<'react-native-orientation'>;
}
