// flow-typed signature: 66582a0e4da4613bd0cd2f73b6f3df6c
// flow-typed version: <<STUB>>/react-navigation-tabs_v0.8.4/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-navigation-tabs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-navigation-tabs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-navigation-tabs/createBottomTabNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/createMaterialTopTabNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/dist' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/dist/navigators/createBottomTabNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/dist/navigators/createMaterialBottomTabNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/dist/navigators/createMaterialTopTabNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/dist/utils/createTabNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/dist/utils/withDimensions' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/dist/views/BottomTabBar' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/dist/views/CrossFadeIcon' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/dist/views/MaterialTopTabBar' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/dist/views/ResourceSavingScene' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/src' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/src/navigators/createBottomTabNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/src/navigators/createMaterialTopTabNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/src/utils/createTabNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/src/utils/withDimensions' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/src/views/BottomTabBar' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/src/views/CrossFadeIcon' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/src/views/MaterialTopTabBar' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/src/views/ResourceSavingScene' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-navigation-tabs/createBottomTabNavigator.js' {
  declare module.exports: $Exports<'react-navigation-tabs/createBottomTabNavigator'>;
}
declare module 'react-navigation-tabs/createMaterialTopTabNavigator.js' {
  declare module.exports: $Exports<'react-navigation-tabs/createMaterialTopTabNavigator'>;
}
declare module 'react-navigation-tabs/dist/index' {
  declare module.exports: $Exports<'react-navigation-tabs/dist'>;
}
declare module 'react-navigation-tabs/dist/index.js' {
  declare module.exports: $Exports<'react-navigation-tabs/dist'>;
}
declare module 'react-navigation-tabs/dist/navigators/createBottomTabNavigator.js' {
  declare module.exports: $Exports<'react-navigation-tabs/dist/navigators/createBottomTabNavigator'>;
}
declare module 'react-navigation-tabs/dist/navigators/createMaterialBottomTabNavigator.js' {
  declare module.exports: $Exports<'react-navigation-tabs/dist/navigators/createMaterialBottomTabNavigator'>;
}
declare module 'react-navigation-tabs/dist/navigators/createMaterialTopTabNavigator.js' {
  declare module.exports: $Exports<'react-navigation-tabs/dist/navigators/createMaterialTopTabNavigator'>;
}
declare module 'react-navigation-tabs/dist/utils/createTabNavigator.js' {
  declare module.exports: $Exports<'react-navigation-tabs/dist/utils/createTabNavigator'>;
}
declare module 'react-navigation-tabs/dist/utils/withDimensions.js' {
  declare module.exports: $Exports<'react-navigation-tabs/dist/utils/withDimensions'>;
}
declare module 'react-navigation-tabs/dist/views/BottomTabBar.js' {
  declare module.exports: $Exports<'react-navigation-tabs/dist/views/BottomTabBar'>;
}
declare module 'react-navigation-tabs/dist/views/CrossFadeIcon.js' {
  declare module.exports: $Exports<'react-navigation-tabs/dist/views/CrossFadeIcon'>;
}
declare module 'react-navigation-tabs/dist/views/MaterialTopTabBar.js' {
  declare module.exports: $Exports<'react-navigation-tabs/dist/views/MaterialTopTabBar'>;
}
declare module 'react-navigation-tabs/dist/views/ResourceSavingScene.js' {
  declare module.exports: $Exports<'react-navigation-tabs/dist/views/ResourceSavingScene'>;
}
declare module 'react-navigation-tabs/src/index' {
  declare module.exports: $Exports<'react-navigation-tabs/src'>;
}
declare module 'react-navigation-tabs/src/index.js' {
  declare module.exports: $Exports<'react-navigation-tabs/src'>;
}
declare module 'react-navigation-tabs/src/navigators/createBottomTabNavigator.js' {
  declare module.exports: $Exports<'react-navigation-tabs/src/navigators/createBottomTabNavigator'>;
}
declare module 'react-navigation-tabs/src/navigators/createMaterialTopTabNavigator.js' {
  declare module.exports: $Exports<'react-navigation-tabs/src/navigators/createMaterialTopTabNavigator'>;
}
declare module 'react-navigation-tabs/src/utils/createTabNavigator.js' {
  declare module.exports: $Exports<'react-navigation-tabs/src/utils/createTabNavigator'>;
}
declare module 'react-navigation-tabs/src/utils/withDimensions.js' {
  declare module.exports: $Exports<'react-navigation-tabs/src/utils/withDimensions'>;
}
declare module 'react-navigation-tabs/src/views/BottomTabBar.js' {
  declare module.exports: $Exports<'react-navigation-tabs/src/views/BottomTabBar'>;
}
declare module 'react-navigation-tabs/src/views/CrossFadeIcon.js' {
  declare module.exports: $Exports<'react-navigation-tabs/src/views/CrossFadeIcon'>;
}
declare module 'react-navigation-tabs/src/views/MaterialTopTabBar.js' {
  declare module.exports: $Exports<'react-navigation-tabs/src/views/MaterialTopTabBar'>;
}
declare module 'react-navigation-tabs/src/views/ResourceSavingScene.js' {
  declare module.exports: $Exports<'react-navigation-tabs/src/views/ResourceSavingScene'>;
}
