// flow-typed signature: e76ee4ec17eb674ab69028a741bb3873
// flow-typed version: <<STUB>>/react-native-simple-toast_v0.0.8/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-simple-toast'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-simple-toast' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-simple-toast/index' {
  declare module.exports: $Exports<'react-native-simple-toast'>;
}
declare module 'react-native-simple-toast/index.js' {
  declare module.exports: $Exports<'react-native-simple-toast'>;
}
