// flow-typed signature: a054ec95ad9fa7f765d69681575bd14f
// flow-typed version: <<STUB>>/react-navigation-redux-helpers_v^1.1.1/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-navigation-redux-helpers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-navigation-redux-helpers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-navigation-redux-helpers/src' {
  declare module.exports: any;
}

declare module 'react-navigation-redux-helpers/src/middleware' {
  declare module.exports: any;
}

declare module 'react-navigation-redux-helpers/src/reducer' {
  declare module.exports: any;
}

declare module 'react-navigation-redux-helpers/src/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-navigation-redux-helpers/src/index' {
  declare module.exports: $Exports<'react-navigation-redux-helpers/src'>;
}
declare module 'react-navigation-redux-helpers/src/index.js' {
  declare module.exports: $Exports<'react-navigation-redux-helpers/src'>;
}
declare module 'react-navigation-redux-helpers/src/middleware.js' {
  declare module.exports: $Exports<'react-navigation-redux-helpers/src/middleware'>;
}
declare module 'react-navigation-redux-helpers/src/reducer.js' {
  declare module.exports: $Exports<'react-navigation-redux-helpers/src/reducer'>;
}
declare module 'react-navigation-redux-helpers/src/types.js' {
  declare module.exports: $Exports<'react-navigation-redux-helpers/src/types'>;
}
