// flow-typed signature: 086e03baede59bb43adf7ccc62806822
// flow-typed version: <<STUB>>/react-native-notifications_v^1.2.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-notifications'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-notifications' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-notifications/index.android' {
  declare module.exports: any;
}

declare module 'react-native-notifications/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-notifications/notification.android' {
  declare module.exports: any;
}

declare module 'react-native-notifications/notification.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-notifications/index.android.js' {
  declare module.exports: $Exports<'react-native-notifications/index.android'>;
}
declare module 'react-native-notifications/index.ios.js' {
  declare module.exports: $Exports<'react-native-notifications/index.ios'>;
}
declare module 'react-native-notifications/notification.android.js' {
  declare module.exports: $Exports<'react-native-notifications/notification.android'>;
}
declare module 'react-native-notifications/notification.ios.js' {
  declare module.exports: $Exports<'react-native-notifications/notification.ios'>;
}
