// flow-typed signature: b55e8f2ac961b4cb11013bfb33132a35
// flow-typed version: <<STUB>>/react-native-progress_v^4.1.2/flow_v0.128.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-progress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-progress' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-progress/Bar' {
  declare module.exports: any;
}


// Filename aliases
declare module 'react-native-progress/Bar.js' {
  declare module.exports: $Exports<'react-native-progress/Bar'>;
}

