// flow-typed signature: 57e06889e2ad0051cd72dd5e7e3f1859
// flow-typed version: <<STUB>>/react-native-hour-format_v1.1.3/flow_v0.128.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-hour-format'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-hour-format' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-hour-format/index' {
  declare module.exports: $Exports<'react-native-hour-format'>;
}
declare module 'react-native-hour-format/index.js' {
  declare module.exports: $Exports<'react-native-hour-format'>;
}
