// flow-typed signature: 1c7f6cfe4daac8fc4a564789a1897119
// flow-typed version: <<STUB>>/react-native-cli_v^2.0.1/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-cli/index' {
  declare module.exports: $Exports<'react-native-cli'>;
}
declare module 'react-native-cli/index.js' {
  declare module.exports: $Exports<'react-native-cli'>;
}
