// flow-typed signature: 5f28b02f43488b49a30587cec69c5a1c
// flow-typed version: <<STUB>>/react-native-haptic-feedback_v1.11.0/flow_v0.128.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-haptic-feedback'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-haptic-feedback' {
  declare module.exports: any;
}

