// flow-typed signature: 104bfc47bb392afbb6af051b37d2ab5a
// flow-typed version: <<STUB>>/react-native-safe-area_v^0.2.3/flow_v0.63.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-safe-area'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-safe-area' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-safe-area/SafeArea.android' {
  declare module.exports: any;
}

declare module 'react-native-safe-area/SafeArea.ios' {
  declare module.exports: any;
}

declare module 'react-native-safe-area/TypeDefinition' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-safe-area/index' {
  declare module.exports: $Exports<'react-native-safe-area'>;
}
declare module 'react-native-safe-area/index.js' {
  declare module.exports: $Exports<'react-native-safe-area'>;
}
declare module 'react-native-safe-area/SafeArea.android.js' {
  declare module.exports: $Exports<'react-native-safe-area/SafeArea.android'>;
}
declare module 'react-native-safe-area/SafeArea.ios.js' {
  declare module.exports: $Exports<'react-native-safe-area/SafeArea.ios'>;
}
declare module 'react-native-safe-area/TypeDefinition.js' {
  declare module.exports: $Exports<'react-native-safe-area/TypeDefinition'>;
}
