// flow-typed signature: c375d2f522b8d4ae2018cea5b8402631
// flow-typed version: <<STUB>>/react-native-popover-view_v3.1.1/flow_v0.128.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-popover-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-popover-view' {
  declare module.exports: any;
}

