// flow-typed signature: 68893b17feb015ef68477ab4af473a7a
// flow-typed version: <<STUB>>/react-native-photo-view_valwx/react-native-photo-view#c58fd6b30/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-photo-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-photo-view' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-photo-view/example/__tests__/index.android' {
  declare module.exports: any;
}

declare module 'react-native-photo-view/example/__tests__/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-photo-view/example/index.android' {
  declare module.exports: any;
}

declare module 'react-native-photo-view/example/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-photo-view/PhotoView.android' {
  declare module.exports: any;
}

declare module 'react-native-photo-view/PhotoView.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-photo-view/example/__tests__/index.android.js' {
  declare module.exports: $Exports<'react-native-photo-view/example/__tests__/index.android'>;
}
declare module 'react-native-photo-view/example/__tests__/index.ios.js' {
  declare module.exports: $Exports<'react-native-photo-view/example/__tests__/index.ios'>;
}
declare module 'react-native-photo-view/example/index.android.js' {
  declare module.exports: $Exports<'react-native-photo-view/example/index.android'>;
}
declare module 'react-native-photo-view/example/index.ios.js' {
  declare module.exports: $Exports<'react-native-photo-view/example/index.ios'>;
}
declare module 'react-native-photo-view/index' {
  declare module.exports: $Exports<'react-native-photo-view'>;
}
declare module 'react-native-photo-view/index.js' {
  declare module.exports: $Exports<'react-native-photo-view'>;
}
declare module 'react-native-photo-view/PhotoView.android.js' {
  declare module.exports: $Exports<'react-native-photo-view/PhotoView.android'>;
}
declare module 'react-native-photo-view/PhotoView.ios.js' {
  declare module.exports: $Exports<'react-native-photo-view/PhotoView.ios'>;
}
