// flow-typed signature: f41d6bf18f4e00bb85955858c1109965
// flow-typed version: <<STUB>>/react-native-webview_v2.0.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-webview'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-webview' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-webview/js/WebView.android' {
  declare module.exports: any;
}

declare module 'react-native-webview/js/WebView.ios' {
  declare module.exports: any;
}

declare module 'react-native-webview/js/WebViewShared' {
  declare module.exports: any;
}

declare module 'react-native-webview/js/WebViewTypes' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-webview/index' {
  declare module.exports: $Exports<'react-native-webview'>;
}
declare module 'react-native-webview/index.js' {
  declare module.exports: $Exports<'react-native-webview'>;
}
declare module 'react-native-webview/js/WebView.android.js' {
  declare module.exports: $Exports<'react-native-webview/js/WebView.android'>;
}
declare module 'react-native-webview/js/WebView.ios.js' {
  declare module.exports: $Exports<'react-native-webview/js/WebView.ios'>;
}
declare module 'react-native-webview/js/WebViewShared.js' {
  declare module.exports: $Exports<'react-native-webview/js/WebViewShared'>;
}
declare module 'react-native-webview/js/WebViewTypes.js' {
  declare module.exports: $Exports<'react-native-webview/js/WebViewTypes'>;
}
