// flow-typed signature: ec0d773e95d04745d47987b4763e9d50
// flow-typed version: <<STUB>>/react-native-screens_v^1.0.0-alpha.23/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-screens'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-screens' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-screens/src/screens.native' {
  declare module.exports: any;
}

declare module 'react-native-screens/src/screens.web' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-screens/src/screens.native.js' {
  declare module.exports: $Exports<'react-native-screens/src/screens.native'>;
}
declare module 'react-native-screens/src/screens.web.js' {
  declare module.exports: $Exports<'react-native-screens/src/screens.web'>;
}
