// flow-typed signature: bc3eac98072569ab3ad896d1e7948e96
// flow-typed version: <<STUB>>/react-native-safe-area_v^0.2.1/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-safe-area'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-safe-area' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-safe-area/index.android' {
  declare module.exports: any;
}

declare module 'react-native-safe-area/index.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-safe-area/index.android.js' {
  declare module.exports: $Exports<'react-native-safe-area/index.android'>;
}
declare module 'react-native-safe-area/index.ios.js' {
  declare module.exports: $Exports<'react-native-safe-area/index.ios'>;
}
