// flow-typed signature: e70237f3f0f0f7216ac66fa336d6aecf
// flow-typed version: <<STUB>>/react-native-document-picker_vgit://github.com/Elyx0/react-native-document-picker.git#v3/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-document-picker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-document-picker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-document-picker/index' {
  declare module.exports: $Exports<'react-native-document-picker'>;
}
declare module 'react-native-document-picker/index.js' {
  declare module.exports: $Exports<'react-native-document-picker'>;
}
