// flow-typed signature: 476e9d4333040bb77059143cf0e400d0
// flow-typed version: <<STUB>>/react-native-video_v5.1.1/flow_v0.128.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-video'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-video' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-video/dom' {
  declare module.exports: any;
}

declare module 'react-native-video/dom/RCTVideo' {
  declare module.exports: any;
}

declare module 'react-native-video/dom/RCTVideoEvent' {
  declare module.exports: any;
}

declare module 'react-native-video/dom/RCTVideoManager' {
  declare module.exports: any;
}

declare module 'react-native-video/dom/resizeModes' {
  declare module.exports: any;
}

declare module 'react-native-video/dom/types' {
  declare module.exports: any;
}

declare module 'react-native-video/DRMType' {
  declare module.exports: any;
}

declare module 'react-native-video/FilterType' {
  declare module.exports: any;
}

declare module 'react-native-video/TextTrackType' {
  declare module.exports: any;
}

declare module 'react-native-video/Video' {
  declare module.exports: any;
}

declare module 'react-native-video/VideoResizeMode' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-video/dom/index' {
  declare module.exports: $Exports<'react-native-video/dom'>;
}
declare module 'react-native-video/dom/index.js' {
  declare module.exports: $Exports<'react-native-video/dom'>;
}
declare module 'react-native-video/dom/RCTVideo.js' {
  declare module.exports: $Exports<'react-native-video/dom/RCTVideo'>;
}
declare module 'react-native-video/dom/RCTVideoEvent.js' {
  declare module.exports: $Exports<'react-native-video/dom/RCTVideoEvent'>;
}
declare module 'react-native-video/dom/RCTVideoManager.js' {
  declare module.exports: $Exports<'react-native-video/dom/RCTVideoManager'>;
}
declare module 'react-native-video/dom/resizeModes.js' {
  declare module.exports: $Exports<'react-native-video/dom/resizeModes'>;
}
declare module 'react-native-video/dom/types.js' {
  declare module.exports: $Exports<'react-native-video/dom/types'>;
}
declare module 'react-native-video/DRMType.js' {
  declare module.exports: $Exports<'react-native-video/DRMType'>;
}
declare module 'react-native-video/FilterType.js' {
  declare module.exports: $Exports<'react-native-video/FilterType'>;
}
declare module 'react-native-video/TextTrackType.js' {
  declare module.exports: $Exports<'react-native-video/TextTrackType'>;
}
declare module 'react-native-video/Video.js' {
  declare module.exports: $Exports<'react-native-video/Video'>;
}
declare module 'react-native-video/VideoResizeMode.js' {
  declare module.exports: $Exports<'react-native-video/VideoResizeMode'>;
}
