// flow-typed signature: a87d6e64a70f93daa0db692cab460aa5
// flow-typed version: <<STUB>>/redux-batched-actions_v^0.3.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-batched-actions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-batched-actions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-batched-actions/lib/index' {
  declare module.exports: any;
}

declare module 'redux-batched-actions/test/index-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-batched-actions/lib/index.js' {
  declare module.exports: $Exports<'redux-batched-actions/lib/index'>;
}
declare module 'redux-batched-actions/test/index-test.js' {
  declare module.exports: $Exports<'redux-batched-actions/test/index-test'>;
}
