// flow-typed signature: 509fbedd9e0c05997706c0f724be1f56
// flow-typed version: <<STUB>>/redux-action-buffer_v^1.2.0/flow_v0.63.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-action-buffer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-action-buffer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'redux-action-buffer/index' {
  declare module.exports: $Exports<'redux-action-buffer'>;
}
declare module 'redux-action-buffer/index.js' {
  declare module.exports: $Exports<'redux-action-buffer'>;
}
