// flow-typed signature: 3d8817b70fbf145990a5dce947df1ec1
// flow-typed version: <<STUB>>/stream_v^0.0.2/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'stream/index' {
  declare module.exports: $Exports<'stream'>;
}
declare module 'stream/index.js' {
  declare module.exports: $Exports<'stream'>;
}
