// flow-typed signature: ba2497f89c8f0cd792edec58fdde3c3a
// flow-typed version: <<STUB>>/string.fromcodepoint_v^0.2.1/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'string.fromcodepoint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'string.fromcodepoint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'string.fromcodepoint/fromcodepoint' {
  declare module.exports: any;
}

// Filename aliases
declare module 'string.fromcodepoint/fromcodepoint.js' {
  declare module.exports: $Exports<'string.fromcodepoint/fromcodepoint'>;
}
