// flow-typed signature: ef552b9df8b5e531c2bb6af7ab70ebd4
// flow-typed version: <<STUB>>/url-parse_v^1.1.8/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'url-parse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'url-parse' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'url-parse/index' {
  declare module.exports: $Exports<'url-parse'>;
}
declare module 'url-parse/index.js' {
  declare module.exports: $Exports<'url-parse'>;
}
