// flow-typed signature: 5e864ad34756398a5ba3f75a7b58d87a
// flow-typed version: <<STUB>>/zulip-markdown-parser_v^1.0.5/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'zulip-markdown-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'zulip-markdown-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'zulip-markdown-parser/__tests__/preview-tests' {
  declare module.exports: any;
}

declare module 'zulip-markdown-parser/emoji_codes' {
  declare module.exports: any;
}

declare module 'zulip-markdown-parser/emoji' {
  declare module.exports: any;
}

declare module 'zulip-markdown-parser/extractedMethods' {
  declare module.exports: any;
}

declare module 'zulip-markdown-parser/fenced_code' {
  declare module.exports: any;
}

declare module 'zulip-markdown-parser/hash_util' {
  declare module.exports: any;
}

declare module 'zulip-markdown-parser/markdown' {
  declare module.exports: any;
}

declare module 'zulip-markdown-parser/marked' {
  declare module.exports: any;
}

declare module 'zulip-markdown-parser/newtest' {
  declare module.exports: any;
}

declare module 'zulip-markdown-parser/parseMarkdown' {
  declare module.exports: any;
}

declare module 'zulip-markdown-parser/test_cases' {
  declare module.exports: any;
}

declare module 'zulip-markdown-parser/test' {
  declare module.exports: any;
}

declare module 'zulip-markdown-parser/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'zulip-markdown-parser/__tests__/preview-tests.js' {
  declare module.exports: $Exports<'zulip-markdown-parser/__tests__/preview-tests'>;
}
declare module 'zulip-markdown-parser/emoji_codes.js' {
  declare module.exports: $Exports<'zulip-markdown-parser/emoji_codes'>;
}
declare module 'zulip-markdown-parser/emoji.js' {
  declare module.exports: $Exports<'zulip-markdown-parser/emoji'>;
}
declare module 'zulip-markdown-parser/extractedMethods.js' {
  declare module.exports: $Exports<'zulip-markdown-parser/extractedMethods'>;
}
declare module 'zulip-markdown-parser/fenced_code.js' {
  declare module.exports: $Exports<'zulip-markdown-parser/fenced_code'>;
}
declare module 'zulip-markdown-parser/hash_util.js' {
  declare module.exports: $Exports<'zulip-markdown-parser/hash_util'>;
}
declare module 'zulip-markdown-parser/markdown.js' {
  declare module.exports: $Exports<'zulip-markdown-parser/markdown'>;
}
declare module 'zulip-markdown-parser/marked.js' {
  declare module.exports: $Exports<'zulip-markdown-parser/marked'>;
}
declare module 'zulip-markdown-parser/newtest.js' {
  declare module.exports: $Exports<'zulip-markdown-parser/newtest'>;
}
declare module 'zulip-markdown-parser/parseMarkdown.js' {
  declare module.exports: $Exports<'zulip-markdown-parser/parseMarkdown'>;
}
declare module 'zulip-markdown-parser/test_cases.js' {
  declare module.exports: $Exports<'zulip-markdown-parser/test_cases'>;
}
declare module 'zulip-markdown-parser/test.js' {
  declare module.exports: $Exports<'zulip-markdown-parser/test'>;
}
declare module 'zulip-markdown-parser/util.js' {
  declare module.exports: $Exports<'zulip-markdown-parser/util'>;
}
