/* @flow */
export const CONTROL_SIZE = 44;
export const STATUSBAR_HEIGHT = 20;
export const NAVBAR_HEIGHT = CONTROL_SIZE + STATUSBAR_HEIGHT;
export const REACTION_HEIGHT = 30;
export const REACTION_SPINNER_OFFSET = REACTION_HEIGHT;
export const LIGHTBOX_FOOTER_OFFSET = 0;
