// flow-typed signature: eaf887ef17716a16e27b3e59c76c89d1
// flow-typed version: <<STUB>>/@remobile/react-native-toast_v^1.0.7/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@remobile/react-native-toast'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@remobile/react-native-toast' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@remobile/react-native-toast/index' {
  declare module.exports: $Exports<'@remobile/react-native-toast'>;
}
declare module '@remobile/react-native-toast/index.js' {
  declare module.exports: $Exports<'@remobile/react-native-toast'>;
}
