// flow-typed signature: b4921e6a6b7477e7d01ce1ad73acea0d
// flow-typed version: <<STUB>>/@react-native-community/netinfo_v3.2.1/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-native-community/netinfo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-native-community/netinfo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-native-community/netinfo/lib/commonjs' {
  declare module.exports: any;
}

declare module '@react-native-community/netinfo/lib/commonjs/internal/deprecatedSubscriptions' {
  declare module.exports: any;
}

declare module '@react-native-community/netinfo/lib/commonjs/internal/deprecatedTypes' {
  declare module.exports: any;
}

declare module '@react-native-community/netinfo/lib/commonjs/internal/deprecatedUtils' {
  declare module.exports: any;
}

declare module '@react-native-community/netinfo/lib/commonjs/internal/nativeInterface' {
  declare module.exports: any;
}

declare module '@react-native-community/netinfo/lib/commonjs/internal/privateTypes' {
  declare module.exports: any;
}

declare module '@react-native-community/netinfo/lib/commonjs/internal/subscriptions' {
  declare module.exports: any;
}

declare module '@react-native-community/netinfo/lib/commonjs/internal/types' {
  declare module.exports: any;
}

declare module '@react-native-community/netinfo/lib/module' {
  declare module.exports: any;
}

declare module '@react-native-community/netinfo/lib/module/internal/deprecatedSubscriptions' {
  declare module.exports: any;
}

declare module '@react-native-community/netinfo/lib/module/internal/deprecatedTypes' {
  declare module.exports: any;
}

declare module '@react-native-community/netinfo/lib/module/internal/deprecatedUtils' {
  declare module.exports: any;
}

declare module '@react-native-community/netinfo/lib/module/internal/nativeInterface' {
  declare module.exports: any;
}

declare module '@react-native-community/netinfo/lib/module/internal/privateTypes' {
  declare module.exports: any;
}

declare module '@react-native-community/netinfo/lib/module/internal/subscriptions' {
  declare module.exports: any;
}

declare module '@react-native-community/netinfo/lib/module/internal/types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-native-community/netinfo/lib/commonjs/index' {
  declare module.exports: $Exports<'@react-native-community/netinfo/lib/commonjs'>;
}
declare module '@react-native-community/netinfo/lib/commonjs/index.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/lib/commonjs'>;
}
declare module '@react-native-community/netinfo/lib/commonjs/internal/deprecatedSubscriptions.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/lib/commonjs/internal/deprecatedSubscriptions'>;
}
declare module '@react-native-community/netinfo/lib/commonjs/internal/deprecatedTypes.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/lib/commonjs/internal/deprecatedTypes'>;
}
declare module '@react-native-community/netinfo/lib/commonjs/internal/deprecatedUtils.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/lib/commonjs/internal/deprecatedUtils'>;
}
declare module '@react-native-community/netinfo/lib/commonjs/internal/nativeInterface.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/lib/commonjs/internal/nativeInterface'>;
}
declare module '@react-native-community/netinfo/lib/commonjs/internal/privateTypes.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/lib/commonjs/internal/privateTypes'>;
}
declare module '@react-native-community/netinfo/lib/commonjs/internal/subscriptions.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/lib/commonjs/internal/subscriptions'>;
}
declare module '@react-native-community/netinfo/lib/commonjs/internal/types.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/lib/commonjs/internal/types'>;
}
declare module '@react-native-community/netinfo/lib/module/index' {
  declare module.exports: $Exports<'@react-native-community/netinfo/lib/module'>;
}
declare module '@react-native-community/netinfo/lib/module/index.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/lib/module'>;
}
declare module '@react-native-community/netinfo/lib/module/internal/deprecatedSubscriptions.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/lib/module/internal/deprecatedSubscriptions'>;
}
declare module '@react-native-community/netinfo/lib/module/internal/deprecatedTypes.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/lib/module/internal/deprecatedTypes'>;
}
declare module '@react-native-community/netinfo/lib/module/internal/deprecatedUtils.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/lib/module/internal/deprecatedUtils'>;
}
declare module '@react-native-community/netinfo/lib/module/internal/nativeInterface.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/lib/module/internal/nativeInterface'>;
}
declare module '@react-native-community/netinfo/lib/module/internal/privateTypes.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/lib/module/internal/privateTypes'>;
}
declare module '@react-native-community/netinfo/lib/module/internal/subscriptions.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/lib/module/internal/subscriptions'>;
}
declare module '@react-native-community/netinfo/lib/module/internal/types.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/lib/module/internal/types'>;
}
