# This should match the iOS Deployment Target
# (project > ZulipMobile > Info in Xcode)
platform :ios, '12.1'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

target 'ZulipMobile' do
  config = use_native_modules!

  use_react_native!(:path => config[:reactNativePath])

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!(
    'Flipper' => '0.75.1',
    'Flipper-Folly' => '2.5.3',
    'Flipper-RSocket' => '1.3.1',
  )
  post_install do |installer|
    flipper_post_install(installer)
  end

  # unimodules provides Expo packages individually.
  use_unimodules!
end
