// flow-typed signature: 6a548cf77d4aa0f0ec8619987a9578e6
// flow-typed version: <<STUB>>/@react-navigation/compat_v5.3.9/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-navigation/compat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-navigation/compat' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-navigation/compat/lib/commonjs/CompatScreen' {
  declare module.exports: any;
}

declare module '@react-navigation/compat/lib/commonjs/createCompatNavigationProp' {
  declare module.exports: any;
}

declare module '@react-navigation/compat/lib/commonjs/createCompatNavigatorFactory' {
  declare module.exports: any;
}

declare module '@react-navigation/compat/lib/commonjs/createSwitchNavigator' {
  declare module.exports: any;
}

declare module '@react-navigation/compat/lib/commonjs/DrawerActions' {
  declare module.exports: any;
}

declare module '@react-navigation/compat/lib/commonjs/helpers' {
  declare module.exports: any;
}

declare module '@react-navigation/compat/lib/commonjs' {
  declare module.exports: any;
}

declare module '@react-navigation/compat/lib/commonjs/NavigationActions' {
  declare module.exports: any;
}

declare module '@react-navigation/compat/lib/commonjs/NavigationEvents' {
  declare module.exports: any;
}

declare module '@react-navigation/compat/lib/commonjs/ScreenPropsContext' {
  declare module.exports: any;
}

declare module '@react-navigation/compat/lib/commonjs/StackActions' {
  declare module.exports: any;
}

declare module '@react-navigation/compat/lib/commonjs/SwitchActions' {
  declare module.exports: any;
}

declare module '@react-navigation/compat/lib/commonjs/types' {
  declare module.exports: any;
}

declare module '@react-navigation/compat/lib/commonjs/useCompatNavigation' {
  declare module.exports: any;
}

declare module '@react-navigation/compat/lib/commonjs/withNavigation' {
  declare module.exports: any;
}

declare module '@react-navigation/compat/lib/commonjs/withNavigationFocus' {
  declare module.exports: any;
}

declare module '@react-navigation/compat/lib/module/CompatScreen' {
  declare module.exports: any;
}

declare module '@react-navigation/compat/lib/module/createCompatNavigationProp' {
  declare module.exports: any;
}

declare module '@react-navigation/compat/lib/module/createCompatNavigatorFactory' {
  declare module.exports: any;
}

declare module '@react-navigation/compat/lib/module/createSwitchNavigator' {
  declare module.exports: any;
}

declare module '@react-navigation/compat/lib/module/DrawerActions' {
  declare module.exports: any;
}

declare module '@react-navigation/compat/lib/module/helpers' {
  declare module.exports: any;
}

declare module '@react-navigation/compat/lib/module' {
  declare module.exports: any;
}

declare module '@react-navigation/compat/lib/module/NavigationActions' {
  declare module.exports: any;
}

declare module '@react-navigation/compat/lib/module/NavigationEvents' {
  declare module.exports: any;
}

declare module '@react-navigation/compat/lib/module/ScreenPropsContext' {
  declare module.exports: any;
}

declare module '@react-navigation/compat/lib/module/StackActions' {
  declare module.exports: any;
}

declare module '@react-navigation/compat/lib/module/SwitchActions' {
  declare module.exports: any;
}

declare module '@react-navigation/compat/lib/module/types' {
  declare module.exports: any;
}

declare module '@react-navigation/compat/lib/module/useCompatNavigation' {
  declare module.exports: any;
}

declare module '@react-navigation/compat/lib/module/withNavigation' {
  declare module.exports: any;
}

declare module '@react-navigation/compat/lib/module/withNavigationFocus' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-navigation/compat/lib/commonjs/CompatScreen.js' {
  declare module.exports: $Exports<'@react-navigation/compat/lib/commonjs/CompatScreen'>;
}
declare module '@react-navigation/compat/lib/commonjs/createCompatNavigationProp.js' {
  declare module.exports: $Exports<'@react-navigation/compat/lib/commonjs/createCompatNavigationProp'>;
}
declare module '@react-navigation/compat/lib/commonjs/createCompatNavigatorFactory.js' {
  declare module.exports: $Exports<'@react-navigation/compat/lib/commonjs/createCompatNavigatorFactory'>;
}
declare module '@react-navigation/compat/lib/commonjs/createSwitchNavigator.js' {
  declare module.exports: $Exports<'@react-navigation/compat/lib/commonjs/createSwitchNavigator'>;
}
declare module '@react-navigation/compat/lib/commonjs/DrawerActions.js' {
  declare module.exports: $Exports<'@react-navigation/compat/lib/commonjs/DrawerActions'>;
}
declare module '@react-navigation/compat/lib/commonjs/helpers.js' {
  declare module.exports: $Exports<'@react-navigation/compat/lib/commonjs/helpers'>;
}
declare module '@react-navigation/compat/lib/commonjs/index' {
  declare module.exports: $Exports<'@react-navigation/compat/lib/commonjs'>;
}
declare module '@react-navigation/compat/lib/commonjs/index.js' {
  declare module.exports: $Exports<'@react-navigation/compat/lib/commonjs'>;
}
declare module '@react-navigation/compat/lib/commonjs/NavigationActions.js' {
  declare module.exports: $Exports<'@react-navigation/compat/lib/commonjs/NavigationActions'>;
}
declare module '@react-navigation/compat/lib/commonjs/NavigationEvents.js' {
  declare module.exports: $Exports<'@react-navigation/compat/lib/commonjs/NavigationEvents'>;
}
declare module '@react-navigation/compat/lib/commonjs/ScreenPropsContext.js' {
  declare module.exports: $Exports<'@react-navigation/compat/lib/commonjs/ScreenPropsContext'>;
}
declare module '@react-navigation/compat/lib/commonjs/StackActions.js' {
  declare module.exports: $Exports<'@react-navigation/compat/lib/commonjs/StackActions'>;
}
declare module '@react-navigation/compat/lib/commonjs/SwitchActions.js' {
  declare module.exports: $Exports<'@react-navigation/compat/lib/commonjs/SwitchActions'>;
}
declare module '@react-navigation/compat/lib/commonjs/types.js' {
  declare module.exports: $Exports<'@react-navigation/compat/lib/commonjs/types'>;
}
declare module '@react-navigation/compat/lib/commonjs/useCompatNavigation.js' {
  declare module.exports: $Exports<'@react-navigation/compat/lib/commonjs/useCompatNavigation'>;
}
declare module '@react-navigation/compat/lib/commonjs/withNavigation.js' {
  declare module.exports: $Exports<'@react-navigation/compat/lib/commonjs/withNavigation'>;
}
declare module '@react-navigation/compat/lib/commonjs/withNavigationFocus.js' {
  declare module.exports: $Exports<'@react-navigation/compat/lib/commonjs/withNavigationFocus'>;
}
declare module '@react-navigation/compat/lib/module/CompatScreen.js' {
  declare module.exports: $Exports<'@react-navigation/compat/lib/module/CompatScreen'>;
}
declare module '@react-navigation/compat/lib/module/createCompatNavigationProp.js' {
  declare module.exports: $Exports<'@react-navigation/compat/lib/module/createCompatNavigationProp'>;
}
declare module '@react-navigation/compat/lib/module/createCompatNavigatorFactory.js' {
  declare module.exports: $Exports<'@react-navigation/compat/lib/module/createCompatNavigatorFactory'>;
}
declare module '@react-navigation/compat/lib/module/createSwitchNavigator.js' {
  declare module.exports: $Exports<'@react-navigation/compat/lib/module/createSwitchNavigator'>;
}
declare module '@react-navigation/compat/lib/module/DrawerActions.js' {
  declare module.exports: $Exports<'@react-navigation/compat/lib/module/DrawerActions'>;
}
declare module '@react-navigation/compat/lib/module/helpers.js' {
  declare module.exports: $Exports<'@react-navigation/compat/lib/module/helpers'>;
}
declare module '@react-navigation/compat/lib/module/index' {
  declare module.exports: $Exports<'@react-navigation/compat/lib/module'>;
}
declare module '@react-navigation/compat/lib/module/index.js' {
  declare module.exports: $Exports<'@react-navigation/compat/lib/module'>;
}
declare module '@react-navigation/compat/lib/module/NavigationActions.js' {
  declare module.exports: $Exports<'@react-navigation/compat/lib/module/NavigationActions'>;
}
declare module '@react-navigation/compat/lib/module/NavigationEvents.js' {
  declare module.exports: $Exports<'@react-navigation/compat/lib/module/NavigationEvents'>;
}
declare module '@react-navigation/compat/lib/module/ScreenPropsContext.js' {
  declare module.exports: $Exports<'@react-navigation/compat/lib/module/ScreenPropsContext'>;
}
declare module '@react-navigation/compat/lib/module/StackActions.js' {
  declare module.exports: $Exports<'@react-navigation/compat/lib/module/StackActions'>;
}
declare module '@react-navigation/compat/lib/module/SwitchActions.js' {
  declare module.exports: $Exports<'@react-navigation/compat/lib/module/SwitchActions'>;
}
declare module '@react-navigation/compat/lib/module/types.js' {
  declare module.exports: $Exports<'@react-navigation/compat/lib/module/types'>;
}
declare module '@react-navigation/compat/lib/module/useCompatNavigation.js' {
  declare module.exports: $Exports<'@react-navigation/compat/lib/module/useCompatNavigation'>;
}
declare module '@react-navigation/compat/lib/module/withNavigation.js' {
  declare module.exports: $Exports<'@react-navigation/compat/lib/module/withNavigation'>;
}
declare module '@react-navigation/compat/lib/module/withNavigationFocus.js' {
  declare module.exports: $Exports<'@react-navigation/compat/lib/module/withNavigationFocus'>;
}
