#!/bin/bash
set -eu
unset CDPATH

# tools/build-webview: WebView assets collection script.

# CAVEAT EMENDATOR: Neither of the build systems have any visibility into this
# script's dependencies -- it is run unconditionally, and must ensure on its own
# that it performs as few actions as possible when nothing has changed.

################################################################################
# Common functions
################################################################################

# print usage message; do not die
usage() {
    cat >&2 <<EOF
usage: $0 [ios | android] --destination DEST [--check-path-name]

Build our webview assets, into directory DEST.

This script is mainly for internal use by our build scripts.  They
go on to use the contents of DEST as the webview-assets folder,
which our message-list WebView relies on for its static assets.
See src/webview/MessageList.js for details.

With --check-path-name, make some defensive checks that DEST has
the form expected from the actual build scripts.

EOF
}

# print error and die
err() {
    echo -e "$0:" $'\e[31merror:\e[0m' "$@" >&2
    exit 1;
}

################################################################################
# Environment
################################################################################

# The project root, for absolutizing paths and accessing auxiliary scripts.
# (Assumed to be one directory up from the script's own location.)
root="$(cd "$(dirname "${BASH_SOURCE[0]}")"/../ && pwd)"

# Ensure that we have access to a functional, modern `readlink`.
. "$root"/tools/lib/ensure-coreutils.sh

# Normalize and absolutize $root.
#
# This must return a name for the project root directory which coincides with
# the one Gradle/Xcode will provide. This is unlikely to be a problem on Linux
# or macOS, but has caused issues on Windows; see GitHub issue #3777.)
root="$(readlink -m "$root")"
readonly root

################################################################################
# Parameters
################################################################################

# Parse arguments. Sloppy, but sufficient for now.
unset target
unset dest
check_path_name=0
while (( $# )); do
    case "$1" in
        --help|-h|help)
            usage; exit 0;;
        android|ios)
            # no check for multiple nouns; oh well
            target="$1"; shift;;
        --destination)
            # note: this doesn't permit an equals sign after `--destination`
            shift; dest="$1"; shift;;
        --check-path-name)
            shift; check_path_name=1;;
        *) usage; exit 2;;
    esac
done

# All arguments are required; complain if any were omitted.
if  [ -z "${target-}" ]; then
    usage; exit 2
elif [ -z "${dest-}" ]; then
    usage; exit 2
fi

# Make $dest absolute, if it isn't already.
dest=$(readlink -m "$dest")

# Argument parsing has concluded; argument variables are no longer mutable.
readonly target dest check_path_name

if (( check_path_name )); then
    case "$target" in
        ios)
            if [ "$(uname)" != "Darwin" ]; then
                err "iOS builds only supported on macOS";
            fi

            # $dest should be copied to `${bundle_root}/webview`.
            #
            # $dest itself must be specified twice in Xcode: once in the invocation
            # of this script, and once in the "Copy Bundle Resources" step. If you
            # change it, you'll need to change it in both places. (And here, of
            # course.)
            if [[ "$dest" != "$root/ios/"* ]]; then
                err "unexpected destination directory '$dest' (expected target in $root/ios/)"
            fi
        ;;
        android)
            # $dest should be copied to `file:///android_asset/webview`.
            #
            # Gradle -- more precisely, the Android Gradle plugin -- is already
            # configured to copy some directory from `build/` into the APK. We
            # determine which directory that is in Gradle, and pass it here.
            if [[ "$dest" != "$root/android/app/build/"* ]]; then
                err "unexpected destination directory '$dest' (expected target in $root/android/app/build/)"
            fi
        ;;
        *) err "impossible target $target";;
    esac

    # As implied above, the ultimate destination of these files should be a
    # directory named `./webview` (relative to the platform-dependent asset
    # root directory).
    #
    # The target directory basename should therefore be 'webview': both build
    # systems will preserve the name they're given here.
    if [[ "$dest" != *"/webview" ]]; then
        err "unexpected destination directory '$dest' (expected basename \"webview\")"
    fi
fi  # if $check_path_name

# Set $staging. This is our local staging directory; once it's compiled, it will
# be synced over to $dest.
readonly staging="$root/src/webview/static"
if [ ! -d "$staging" ]; then
    err "cannot find asset staging directory '$staging'";
fi


################################################################################
# Pre-sync: additional build steps
################################################################################

# Currently none, but this is where they'll go.
#
# TODO: Use something like `make -f src/webview/static.Makefile`, to ensure that
#   complicated build steps are not run unconditionally.
#
# TODO: split assets into build-time-generated and build-time-static?
#   - rsync can sync from multiple directories, but has no collision-detection
#   - might be too many layers of abstraction


################################################################################
# Sync
################################################################################

# Sync the directory structure, preserving metadata. (We ignore any files named
# 'README.md'; these should be strictly informative.)
#
# We use `rsync` here, as it will skip unchanged files.
mkdir -p "$dest"
rsync -a --no-D --delete --delete-excluded --exclude=README.md "$staging/." "$dest"



################################################################################
# Post-sync: additional build steps
################################################################################

# None yet.
