#!/bin/bash
set -e

usage () {
    cat <<EOF >&2
usage: bump-version VERSION_NAME

Updates the version number in our Android and iOS build configs.

Example:
  bump-version 17.1.98
EOF
    exit 2
}

version_name="$1";
shift || usage;
shift && usage;

version_code="${version_name##*.}"

perl -i -0pe '
s/versionCode \K[0-9]+/'"$version_code"'/;
s/versionName "\K[0-9.]+/'"$version_name"'/;
' android/app/build.gradle

perl -i -0pe '
s|<key>CFBundleShortVersionString</key> \s*
  <string>\K [0-9.]+
 |'"$version_name"'|xs
' ios/ZulipMobile/Info.plist
