#!/bin/bash
set -e

## CLI PARSING

usage() {
    cat >&2 <<EOF
usage: tools/checkout-keystore

EOF
    exit 2
}

if (( ${#} )); then
    usage
fi


## EXECUTION

rootdir=$(git rev-parse --show-toplevel)
cleartext="${rootdir}"/android/release.keystore
cryptotext="${rootdir}"/android/release.keystore.gpg

gpg -d -o "${cleartext}" "${cryptotext}"

wait_min=15
(
    sleep "$(( ${wait_min} * 60 ))"
    rm -f "${cleartext}"
) &

cat >&2 <<EOF

Wrote decrypted file: ${cleartext}

This file will be deleted in ${wait_min} minutes.
EOF
