#!/usr/bin/env bash
set -eu

ROOT_DIR=$(git rev-parse --show-toplevel)

pod_install() {
    [[ "$OSTYPE" == "darwin"* ]] \
        || return 0

    if ! hash pod 2>/dev/null; then
        cat >&2 <<EOF
The Zulip mobile app requires CocoaPods for its iOS build. Please
install it, following the instructions at
https://guides.cocoapods.org/using/getting-started.html.

Then, rerun yarn.
EOF
        exit 1
    fi

    # Do nothing if the installed pods already match the Podfile.lock.
    # If they don't match, run `pod install`. Conditional copied from
    # the `[CP] Check Pods Manifest.lock` shell-script build phase in
    # `project.pbxproj`.
    if diff "$ROOT_DIR/ios/Podfile.lock" "$ROOT_DIR/ios/Pods/Manifest.lock" > /dev/null; then
        echo "Skipping \`pod install\` (pods already in sync with Podfile.lock)"
    else
        pod install --project-directory="$ROOT_DIR/ios"
    fi
}

jetify() {
    node_modules/.bin/jetify
}

pod_install

jetify

echo "tools/postinstall finished with no errors!"
