#!/bin/bash

shopt -s globstar

this_file=$(readlink -f "$0")
rootdir=${this_file%/*/*}

bindir=$rootdir/node_modules/.bin

import_pairs()
{
    "$bindir"/flow get-imports --json "$rootdir"/src/**/*.js \
        | jq '.[] | .requirements[] | [.import, .path]
              | map(ltrimstr("'"$rootdir"'/")) | join(" ") ' \
             -r
}

sorted_files()
{
    import_pairs | tsort 2>/dev/null
}

sorted_ourfiles()
{
    grep -l '@flow' -- $(sorted_files | grep ^src/.*js$)
}

with_flow()
{
    grep '@flow' -- $(sorted_files | grep ^src/.*js$)
}

todo()
{
    with_flow | number_lines | grep -v '@flow strict '
}

number_lines()
{
    nl -ba -nln -w3 -s' '
}

case "$1" in
    pairs) import_pairs;;
    ''|list) sorted_ourfiles;;
    flow) with_flow | number_lines;;
    todo) todo;;
esac
