#!/usr/bin/env bash
oldjs=$(<./src/webview/js/generatedEs3.js)

tools/generate-webview-js

newjs=$(<./src/webview/js/generatedEs3.js)

if [ "$oldjs" != "$newjs" ]; then
    echo "generatedEs3.js is not updated with current js file."
    exit 1
fi
