export const BATCH_ACTIONS = 'BATCH_ACTIONS';

export const APP_ACTIVITY = 'APP_ACTIVITY';
export const APP_ONLINE = 'APP_ONLINE';
export const APP_ORIENTATION = 'APP_ORIENTATION';
export const APP_STATE = 'APP_STATE';

export const REALM_ADD = 'REALM_ADD';
export const SET_AUTH_TYPE = 'SET_AUTH_TYPE';
export const ACCOUNT_ADD_SUCCEEDED = 'ACCOUNT_ADD_SUCCEEDED';
export const ACCOUNT_REMOVE = 'ACCOUNT_REMOVE';
export const ACCOUNT_SWITCH = 'ACCOUNT_SWITCH';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const HTTP_UNAUTHORIZED = 'HTTP_UNAUTHORIZED';
export const LOGOUT = 'LOGOUT';

export const INIT_ROUTES = 'INIT_ROUTES';
export const PUSH_ROUTE = 'PUSH_ROUTE';
export const POP_ROUTE = 'POP_ROUTE';

export const REALM_INIT = 'REALM_INIT';
export const SWITCH_NARROW = 'SWITCH_NARROW';

export const INITIAL_FETCH_COMPLETE = 'INITIAL_FETCH_COMPLETE';
export const INIT_STREAMS = 'INIT_STREAMS';
export const INIT_SUBSCRIPTIONS = 'INIT_SUBSCRIPTIONS';
export const INIT_USERS = 'INIT_USERS';

export const EVENT_REGISTERED = 'EVENT_REGISTERED';
export const EVENT_NEW_MESSAGE = 'EVENT_NEW_MESSAGE';
export const EVENT_STREAM_ADD = 'EVENT_STREAM_ADD';
export const EVENT_STREAM_REMOVE = 'EVENT_STREAM_REMOVE';
export const EVENT_STREAM_UPDATE = 'EVENT_STREAM_UPDATE';
export const EVENT_SUBSCRIPTION_ADD = 'EVENT_SUBSCRIPTION_ADD';
export const EVENT_SUBSCRIPTION_REMOVE = 'EVENT_SUBSCRIPTION_REMOVE';
export const EVENT_SUBSCRIPTION_UPDATE = 'EVENT_SUBSCRIPTION_UPDATE';
export const EVENT_SUBSCRIPTION_PEER_ADD = 'EVENT_SUBSCRIPTION_PEER_ADD';
export const EVENT_SUBSCRIPTION_PEER_REMOVE = 'EVENT_SUBSCRIPTION_PEER_REMOVE';
export const EVENT_UPDATE_MESSAGE = 'EVENT_UPDATE_MESSAGE';
export const EVENT_REACTION_ADD = 'EVENT_REACTION_ADD';
export const EVENT_REACTION_REMOVE = 'EVENT_REACTION_REMOVE';
export const EVENT_PRESENCE = 'EVENT_PRESENCE';
export const EVENT_TYPING_START = 'EVENT_TYPING_START';
export const EVENT_TYPING_STOP = 'EVENT_TYPING_STOP';
export const EVENT_UPDATE_MESSAGE_FLAGS = 'EVENT_UPDATE_MESSAGE_FLAGS';
export const EVENT_USER_ADD = 'EVENT_USER_ADD';
export const EVENT_USER_REMOVE = 'EVENT_USER_REMOVE';
export const EVENT_USER_UPDATE = 'EVENT_USER_UPDATE';

export const MESSAGE_FETCH_START = 'MESSAGE_FETCH_START';
export const MESSAGE_FETCH_SUCCESS = 'MESSAGE_FETCH_SUCCESS';

export const PRESENCE_RESPONSE = 'PRESENCE_RESPONSE';
export const GET_USER_RESPONSE = 'GET_USER_RESPONSE';
export const MARK_MESSAGES_READ = 'MARK_MESSAGES_READ';
export const SETTINGS_CHANGE = 'SETTINGS_CHANGE';
