/* @flow */
export const REHYDRATE = 'persist/REHYDRATE';

export const APP_ONLINE = 'APP_ONLINE';
export const APP_ORIENTATION = 'APP_ORIENTATION';
export const APP_STATE = 'APP_STATE';
export const APP_REFRESH = 'APP_REFRESH';

export const REALM_ADD = 'REALM_ADD';
export const ACCOUNT_ADD_SUCCEEDED = 'ACCOUNT_ADD_SUCCEEDED';
export const ACCOUNT_REMOVE = 'ACCOUNT_REMOVE';
export const ACCOUNT_SWITCH = 'ACCOUNT_SWITCH';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const HTTP_UNAUTHORIZED = 'HTTP_UNAUTHORIZED';
export const LOGOUT = 'LOGOUT';

export const REALM_INIT = 'REALM_INIT';
export const SWITCH_NARROW = 'SWITCH_NARROW';

export const INIT_SAFE_AREA_INSETS = 'INIT_SAFE_AREA_INSETS';
export const INITIAL_FETCH_START = 'INITIAL_FETCH_START';
export const INITIAL_FETCH_COMPLETE = 'INITIAL_FETCH_COMPLETE';
export const INIT_STREAMS = 'INIT_STREAMS';
export const INIT_SUBSCRIPTIONS = 'INIT_SUBSCRIPTIONS';
export const INIT_REALM_EMOJI = 'INIT_REALM_EMOJI';
export const INIT_REALM_FILTER = 'INIT_REALM_FILTER';
export const INIT_TOPICS = 'INIT_TOPICS';

export const EVENT_NEW_MESSAGE = 'EVENT_NEW_MESSAGE';
export const EVENT_MESSAGE_DELETE = 'EVENT_MESSAGE_DELETE';
export const EVENT_STREAM_ADD = 'EVENT_STREAM_ADD';
export const EVENT_STREAM_REMOVE = 'EVENT_STREAM_REMOVE';
export const EVENT_STREAM_UPDATE = 'EVENT_STREAM_UPDATE';
export const EVENT_STREAM_OCCUPY = 'EVENT_STREAM_OCCUPY';
export const EVENT_SUBSCRIPTION_ADD = 'EVENT_SUBSCRIPTION_ADD';
export const EVENT_SUBSCRIPTION_REMOVE = 'EVENT_SUBSCRIPTION_REMOVE';
export const EVENT_SUBSCRIPTION_UPDATE = 'EVENT_SUBSCRIPTION_UPDATE';
export const EVENT_SUBSCRIPTION_PEER_ADD = 'EVENT_SUBSCRIPTION_PEER_ADD';
export const EVENT_SUBSCRIPTION_PEER_REMOVE = 'EVENT_SUBSCRIPTION_PEER_REMOVE';
export const EVENT_UPDATE_MESSAGE = 'EVENT_UPDATE_MESSAGE';
export const EVENT_REACTION_ADD = 'EVENT_REACTION_ADD';
export const EVENT_REACTION_REMOVE = 'EVENT_REACTION_REMOVE';
export const EVENT_PRESENCE = 'EVENT_PRESENCE';
export const EVENT_TYPING_START = 'EVENT_TYPING_START';
export const EVENT_TYPING_STOP = 'EVENT_TYPING_STOP';
export const EVENT_UPDATE_MESSAGE_FLAGS = 'EVENT_UPDATE_MESSAGE_FLAGS';
export const EVENT_USER_ADD = 'EVENT_USER_ADD';
export const EVENT_USER_REMOVE = 'EVENT_USER_REMOVE';
export const EVENT_USER_UPDATE = 'EVENT_USER_UPDATE';
export const EVENT_MUTED_TOPICS = 'EVENT_MUTED_TOPICS';

export const EVENT_USER_GROUP_ADD = 'EVENT_USER_GROUP_ADD';
export const EVENT_USER_GROUP_REMOVE = 'EVENT_USER_GROUP_REMOVE';
export const EVENT_USER_GROUP_UPDATE = 'EVENT_USER_GROUP_UPDATE';
export const EVENT_USER_GROUP_ADD_MEMBERS = 'EVENT_USER_GROUP_ADD_MEMBERS';
export const EVENT_USER_GROUP_REMOVE_MEMBERS = 'EVENT_USER_GROUP_REMOVE_MEMBERS';

export const MESSAGE_FETCH_START = 'MESSAGE_FETCH_START';
export const MESSAGE_FETCH_COMPLETE = 'MESSAGE_FETCH_COMPLETE';

export const PRESENCE_RESPONSE = 'PRESENCE_RESPONSE';
export const GET_USER_RESPONSE = 'GET_USER_RESPONSE';
export const MARK_MESSAGES_READ = 'MARK_MESSAGES_READ';
export const SETTINGS_CHANGE = 'SETTINGS_CHANGE';
export const DEBUG_FLAG_TOGGLE = 'DEBUG_FLAG_TOGGLE';

export const SAVE_TOKEN_PUSH = 'SAVE_TOKEN_PUSH';
export const DELETE_TOKEN_PUSH = 'DELETE_TOKEN_PUSH';

export const EVENT_REALM_EMOJI_UPDATE = 'EVENT_REALM_EMOJI_UPDATE';
export const EVENT_REALM_FILTER_UPDATE = 'EVENT_REALM_FILTER_UPDATE';

export const EVENT_UPDATE_DISPLAY_SETTINGS = 'EVENT_UPDATE_DISPLAY_SETTINGS';
export const EVENT_UPDATE_GLOBAL_NOTIFICATIONS_SETTINGS =
  'EVENT_UPDATE_GLOBAL_NOTIFICATIONS_SETTINGS';

export const START_EDIT_MESSAGE = 'START_EDIT_MESSAGE';
export const CANCEL_EDIT_MESSAGE = 'CANCEL_EDIT_MESSAGE';

export const INIT_ALERT_WORDS = 'INIT_ALERT_WORDS';

export const MESSAGE_SEND_START = 'MESSAGE_SEND_START';
export const MESSAGE_SEND_COMPLETE = 'MESSAGE_SEND_COMPLETE';

export const TOGGLE_OUTBOX_SENDING = 'TOGGLE_OUTBOX_SENDING';
export const DELETE_OUTBOX_MESSAGE = 'DELETE_OUTBOX_MESSAGE';

export const DRAFT_ADD = 'DRAFT_ADD';
export const DRAFT_REMOVE = 'DRAFT_REMOVE';

export const CLEAR_TYPING = 'CLEAR_TYPING';
