export const APP_ACTIVITY = 'APP_ACTIVITY';
export const APP_ONLINE = 'APP_OFFLINE';
export const APP_OFFLINE = 'APP_OFFLINE';

export const REALM_ADD = 'REALM_ADD';
export const SET_AUTH_TYPE = 'SET_AUTH_TYPE';
export const ACCOUNT_ADD_SUCCEEDED = 'ACCOUNT_ADD_SUCCEEDED';
export const ACCOUNT_REMOVE = 'ACCOUNT_REMOVE';
export const ACCOUNT_SELECT = 'ACCOUNT_SELECT';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const HTTP_UNAUTHORIZED = 'HTTP_UNAUTHORIZED';
export const LOGOUT = 'LOGOUT';

export const INIT_ROUTES = 'INIT_ROUTES';
export const PUSH_ROUTE = 'PUSH_ROUTE';
export const POP_ROUTE = 'POP_ROUTE';

export const OPEN_STREAM_SIDEBAR = 'OPEN_STREAM_SIDEBAR';
export const CLOSE_STREAM_SIDEBAR = 'CLOSE_STREAM_SIDEBAR';

export const REALM_INIT = 'REALM_INIT';

export const EVENT_NEW_MESSAGE = 'EVENT_NEW_MESSAGE';
export const EVENTS_REGISTERED = 'EVENTS_REGISTERED';
export const EVENT_HEARTBEAT = 'EVENTS_HEARTBEAT';
export const EVENT_PRESENCE = 'EVENTS_PRESENCE';
export const EVENT_UPDATE_MESSAGE_FLAGS = 'EVENT_UPDATE_MESSAGE_FLAGS';

export const STREAM_FETCHING_MESSAGES = 'STREAM_FETCHING_MESSAGES';
export const STREAM_FETCHED_MESSAGES = 'STREAM_FETCHED_MESSAGES';
export const STREAM_FETCHING_FAILED = 'STREAM_FETCHING_FAILED';
export const STREAM_SET_MESSAGES = 'STREAM_SET_MESSAGES';

export const PRESENCE_RESPONSE = 'PRESENCE_RESPONSE';
export const GET_USER_RESPONSE = 'GET_USER_RESPONSE';
