export const APP_ACTIVITY = 'APP_ACTIVITY';
export const APP_ONLINE = 'APP_OFFLINE';
export const APP_OFFLINE = 'APP_OFFLINE';

export const REALM_ADD = 'REALM_ADD';
export const SET_AUTH_TYPE = 'SET_AUTH_TYPE';
export const ACCOUNT_ADD_SUCCEEDED = 'ACCOUNT_ADD_SUCCEEDED';
export const ACCOUNT_REMOVE = 'ACCOUNT_REMOVE';
export const ACCOUNT_SWITCH = 'ACCOUNT_SWITCH';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const HTTP_UNAUTHORIZED = 'HTTP_UNAUTHORIZED';
export const LOGOUT = 'LOGOUT';

export const INIT_ROUTES = 'INIT_ROUTES';
export const PUSH_ROUTE = 'PUSH_ROUTE';
export const POP_ROUTE = 'POP_ROUTE';

export const REALM_INIT = 'REALM_INIT';
export const SWITCH_NARROW = 'SWITCH_NARROW';

export const EVENT_NEW_MESSAGE = 'EVENT_NEW_MESSAGE';
export const EVENT_SUBSCRIPTION_ADD = 'EVENT_SUBSCRIPTION_ADD';
export const EVENT_SUBSCRIPTION_REMOVE = 'EVENT_SUBSCRIPTION_REMOVE';
export const EVENT_UPDATE_MESSAGE = 'EVENT_UPDATE_MESSAGE';
export const EVENTS_REGISTERED = 'EVENTS_REGISTERED';
export const EVENT_HEARTBEAT = 'EVENTS_HEARTBEAT';
export const EVENT_REACTION = 'EVENTS_REACTION';
export const EVENT_PRESENCE = 'EVENTS_PRESENCE';
export const EVENT_UPDATE_MESSAGE_FLAGS = 'EVENT_UPDATE_MESSAGE_FLAGS';

export const MESSAGE_FETCH_START = 'MESSAGE_FETCH_START';
export const MESSAGE_FETCH_SUCCESS = 'MESSAGE_FETCH_SUCCESS';

export const PRESENCE_RESPONSE = 'PRESENCE_RESPONSE';
export const GET_USER_RESPONSE = 'GET_USER_RESPONSE';
