// flow-typed signature: e604e34523d140e30d3a06c06763ac9c
// flow-typed version: <<STUB>>/@rollup/plugin-babel_v5.2.0/flow_v0.105.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@rollup/plugin-babel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@rollup/plugin-babel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@rollup/plugin-babel/dist/index.es' {
  declare module.exports: any;
}

declare module '@rollup/plugin-babel/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module '@rollup/plugin-babel/dist/index.es.js' {
  declare module.exports: $Exports<'@rollup/plugin-babel/dist/index.es'>;
}
declare module '@rollup/plugin-babel/dist/index' {
  declare module.exports: $Exports<'@rollup/plugin-babel/dist'>;
}
declare module '@rollup/plugin-babel/dist/index.js' {
  declare module.exports: $Exports<'@rollup/plugin-babel/dist'>;
}
